### ISSUE TITLE
Control+Selecting multiple words to Bold/Italic

### ISSUE THREAD

**Issue by Hawkers** [Ionaru/easy-markdown-editor#10]
When you hold control to select multiple words to apply a style like bold, they are grouped and repeated in place of each word. Maybe selections should be limited to concurrent words?

**Comment by Ionaru** [comment]
I agree, this is how the GitHub editor works as well.

**Comment by Ionaru** [comment]
This has been fixed in 18c03985ead4a5820557fb18f1f384f3ffa985ab, which is in release 2.2.2
