### ISSUE TITLE
Confused about debug/simplemde.css vs src/css/simplemde.css

### ISSUE THREAD

**Issue by jfly** [Ionaru/easy-markdown-editor#108]
(Cross posting from https://github.com/sparksuite/simplemde-markdown-editor/issues/578)

These two files seem to be pretty different, and in fact, I can only get EasyMDE working when I use `easymde/dist/easymde.min.css`. Is it possible some important stuff was accidentally deleted from `easymde/src/css/easymde.css`?

Here's what I see when I use `easymde/src/css/easymde.css`:

![image](https://user-images.githubusercontent.com/277474/62029622-f891e600-b197-11e9-8955-9858b9f0184b.png)

If you'd like me to create a simple standalone reproduction, I can try to do that, but I suspect I just need to understand the purpose of the debug css vs the src css file.

**Comment by Ionaru** [comment]
The .CSS file in the src folder does not contain all the styles needed to run the editor. Those extra styles are injected into the file by gulp during the build step. The file then gets minified and saved as dist/easymde.min.css

So you are right that you can't run the editor with just easymde.css from the src folder, this is normal behaviour.

**Comment by jfly** [comment]
Got it, thank you!
