### ISSUE TITLE
Auto preview and quote color

### ISSUE THREAD

**Issue by G2G2G2G** [Ionaru/easy-markdown-editor#110]
I don't do web code much, did I do this the correct way to have it automatically be on the "preview" mode? (it works, just checking if it is the right way)
```
var easyMDE = new EasyMDE({element: document.getElementById('estftextareaMDE')});
easyMDE.togglePreview();

```

When you quote something it doesn't have a background which is normal in markdown to have one, I added:
`blockquote {
    background-color:#e6e6e6;
}`

Is there a different way to go about these or is this the correct way? I want to be sure I can upgrade versions if needed and not have to change things.
Thanks

**Comment by vanillajonathan** [comment]
The blockquote is styled with the `cm-quote` CSS class.
https://github.com/Ionaru/easy-markdown-editor/blob/master/src/css/easymde.css#L335-L338

**Comment by G2G2G2G** [comment]
This was 3 years ago, but you still didn't answer correctly, the blockquote in the "preview" mode doesn't have any css classes.
What you pasted is the SPAN that is styled with cm-quote during the editing mode, not preview mode.
