### ISSUE TITLE
How to make it render newline character in preview mode?

### ISSUE THREAD

**Issue by SuperManEver** [Ionaru/easy-markdown-editor#111]
I have a string

 `'# Hello world \n\n\n**bold text** \n some other text'`

passed as a value. In Editor view, I see multiple newline characters but if I take a look in preview multiple newline characters don't preserve

is there any config options which can be used to configure preview to treat `\n` as newline character and display as many empty lines as there are a newline characters??

**Comment by AlisonZXQ** [comment]
hello, how did you solve it finally?
