### ISSUE TITLE
Detach the fork and turn it into a standalone repository

### ISSUE THREAD

**Issue by A-312** [Ionaru/easy-markdown-editor#128]
Hi,

The last commit of original repository is [4 years ago](https://github.com/sparksuite/simplemde-markdown-editor) and this branch is 312 commits ahead. Why do you stay has fork ?

Because : 

> In open source projects, forks are often used to iterate on ideas or changes before they are offered back to the upstream repository for everyone to benefit from.

I understand that the base of the work is not your, but if you keep the LICENSE pointed to `sparksuite/simplemde-markdown-editor`, you don't not have to keep fork state.

Some fonctionnality are disabled in fork, like search in code, see : https://github.com/Ionaru/easy-markdown-editor/search?q=toolbar&type=Code

![image](https://user-images.githubusercontent.com/18501150/68699253-f6a33580-0582-11ea-9e68-c2c5f14d6fd5.png)

See : https://stackoverflow.com/a/27718433/2226755 -> https://help.github.com/en/github/setting-up-and-managing-your-github-profile/why-are-my-contributions-not-showing-up-on-my-profile#commit-was-made-in-a-fork

And [About forks](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/about-forks) : 

> If you want to create a new repository from the contents of an existing repository but don't want to merge your changes upstream in the future, you can duplicate the repository or, if the repository is a template, use the repository as a template. For more information, see "[Duplicating a repository](https://help.github.com/en/github/creating-cloning-and-archiving-repositories/duplicating-a-repository)" and "[Creating a repository from a template](https://help.github.com/en/github/creating-cloning-and-archiving-repositories/creating-a-repository-from-a-template)".

**Comment by Ionaru** [comment]
There is one more reason for this being a fork: exposure.

People searching for javascript markdown editors will often find SimpleMDE simply because it's the biggest, with this repo being the largest fork, people often find it by looking at the [network graph](https://github.com/sparksuite/simplemde-markdown-editor/network).

Unless there are some really strong arguements for detaching from SimpleMDE, I would rather keep it the way it is.

**Comment by A-312** [comment]
> There is one more reason for this being a fork: exposure.
> 
> People searching for javascript markdown editors will often find SimpleMDE simply because it's the biggest, with this repo being the largest fork, people often find it by looking at the [network graph](https://github.com/sparksuite/simplemde-markdown-editor/network).

The first thing I do is watching issue to see issue like this one : https://github.com/sparksuite/simplemde-markdown-editor/issues/740

> 
> Unless there are some really strong arguements for detaching from SimpleMDE, I would rather keep it the way it is.

I tought that "Search in code" is strong one.

**Comment by A-312** [comment]
> There is one more reason for this being a fork: exposure.

If you keep another repository fork for `sparksuite/simplemde-markdown-editor` on github, you can add remote on easymde to your fork. This one will appear like a fork with all of your commit.

**Comment by sn3p** [comment]
I found myself in the same position yesterday, not able to search the repo on GitHub.

Could detach and keep the fork with a notice and link to the detached repo. Just a thought.

**Comment by Ionaru** [comment]
That's a good idea.

**Comment by Ionaru** [comment]
Fork is now detached!
