### ISSUE TITLE
Check boxes always have bullets in font of them

### ISSUE THREAD

**Issue by arlenarlenarlen** [Ionaru/easy-markdown-editor#136]
**Describe the bug**
The way check boxes are typically work is 

```
- [ ] unchecked item
- [x] checked item
```

- [ ] unchecked
- [x] checked

However, check boxes are rendering with bullets.

**To Reproduce**
1. Go to https://easymde.tk/
2. Type `- [ ] unchecked item` or `- [x] checked item`
3. Toggle preview
4. Check boxes have bullets in front of them.

**Expected behavior**
Check boxes should not have bullets

**Screenshots**
<img width="477" alt="Screen Shot 2020-01-01 at 17 03 45" src="https://user-images.githubusercontent.com/3126011/71648412-c4779f80-2cb8-11ea-8915-5583b2ef9cbc.png">

<img width="450" alt="Screen Shot 2020-01-01 at 17 03 51" src="https://user-images.githubusercontent.com/3126011/71648415-c8a3bd00-2cb8-11ea-8162-dc2853017386.png">

**Version information**
- OS: macOS 10.14.5
- Browser: Chrome 78
- EasyMDE version: 2.8.0

**Additional context**
First experienced this in Standard Notes, but it's reproducible using https://easymde.tk/

**Comment by mxgl** [comment]
This is a bug with [marked.js](https://github.com/markedjs/marked/issues), which EasyMDE uses for its rendering. You should make this bug there and use [their demo](https://marked.js.org/demo/?text=-%20%5B%20%5D%20unchecked%0A-%20%5Bx%5D%20checked%0A-%20%5B%20%5D%20more%20items%0A-%20%5Bx%5D%20even%0A-%20%5Bx%5D%20more%0A-%5B%20%5D%20items%0A-%5Bx%5D%20!!&options=%7B%0A%20%22baseUrl%22%3A%20null%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22headerIds%22%3A%20true%2C%0A%20%22headerPrefix%22%3A%20%22%22%2C%0A%20%22highlight%22%3A%20null%2C%0A%20%22langPrefix%22%3A%20%22language-%22%2C%0A%20%22mangle%22%3A%20true%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22sanitize%22%3A%20false%2C%0A%20%22sanitizer%22%3A%20null%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22smartLists%22%3A%20false%2C%0A%20%22smartypants%22%3A%20false%2C%0A%20%22xhtml%22%3A%20false%0A%7D&version=master)

**Comment by Ionaru** [comment]
Have a look on https://easymde.tk/next to see what check boxes look like now.
