### ISSUE TITLE
Support custom markup for icons in toolbar

### ISSUE THREAD

**Issue by kolaente** [Ionaru/easy-markdown-editor#137]
**Is your feature request related to a problem? Please describe.**
I'm working on a Vue.js project where the icons are loaded as svgs with the [Font Awesome vue package](https://github.com/FortAwesome/vue-fontawesome).
Easymde is set up in a way which assumes the "classic" loading of font awesome icons, with `<i class=""/>` tags. The Fontawesome vue package is incompatible with this.

**Describe the solution you'd like**
Ideally, easymde would provide a way to let me specify the markup for an icon for a toolbar entry.
This could look something like this:
```js
var easyMDE = new EasyMDE({
	toolbar: [{
			name: "bold",
			action: EasyMDE.toggleBold,
			title: "Bold",
                        markup: '<svg .../>'
		}
	]
});
```
(This would mean for me to redefne each toolbar entry, but as I'm refining the toolbar itself already for the layout, that's not that much of a deal)

**Describe alternatives you've considered**
An alternative would be to also load font awesome font files, which would create some clutter imho.

**Comment by olavgg** [comment]
I would prefer that icons was embedded as SVG images, just like [Trix](https://trix-editor.org/) does. Relying on Font Awesome for just ~10 icons is in my opinion overkill.

**Comment by kolaente** [comment]
@olavgg You mean including the icons as svg right from the start?

IMHO a good idea, but this would probably break compatibility with simpleMDE (It would probably still be worth doing).

**Comment by kolaente** [comment]
Relevant parts needed to be extended would probably only be https://github.com/Ionaru/easy-markdown-editor/blob/master/src/js/easymde.js#L187-L192

I'll try to give it a go anytime soon.

**Comment by A-312** [comment]
You can already use svg with `background:url(icon.svg);`.

**Comment by kolaente** [comment]
@A-312 you mean by manually reimplementing the icons for fontawesome classes?

**Comment by A-312** [comment]
Rewrite FA class or add css class in your button

**Comment by kolaente** [comment]
I guess that could be a solution, but feels a lot like a workaround.

**Comment by kolaente** [comment]
I've put up a pr: #168
