### ISSUE TITLE
Cannot bundle code with webpack that imports EasyMDE

### ISSUE THREAD

**Issue by syropian** [Ionaru/easy-markdown-editor#14]
### I'm submitting a...
- [x] Bug report
- [ ] Feature request

### Reproduction steps
1. `npm install easymde --save`
2. Added `import EasyMDE from 'easymde'`
2. Compiled the component that imports it using webpack

### Version information
Node: 8.9.4
NPM: 5.6.0
EasyMDE version: 2.0.1

Issue:
I currently have webpack set up as my app's bundler, and I've had no problems so far with any other modules, but after installing and trying to use easymde, `babel-loader` freaks out and says it cannot find the module, even though I confirmed it's present in `node_modules`. I tested with another module and it worked fine. Could it be because your package.json `main` field points to the dev build of the module?

**Comment by syropian** [comment]
Confirmed, it's a buggy line in the package.json. Manually changed it and it fixed it. Will submit a PR.

**Comment by Ionaru** [comment]
I'll deploy it soon, in the meantime you can install the latest version using `npm install easymde@next`. That tag will always be up-to-date with the development branch.

**Comment by syropian** [comment]
@Ionaru Good tip, thanks!
