### ISSUE TITLE
Could you please provide an "index.html" template to work from in the future?

### ISSUE THREAD

**Issue by lexterror** [Ionaru/easy-markdown-editor#144]
Hi, I'm trying to put together an html page for easy-markdown-editor and I'm having various issues. 

1. Some Icons don't show when using the keyword "toolbar"
2. There's some "xxxxxx" text at the top of the page when typing.
3. The Side by Side view shows top/bottom.

It would be great if you could provide a default HTML page that I could use to work from.

Thank you!

**Comment by lexterror** [comment]
I was using the wrong JS/CSS files...

**Comment by ylc395** [comment]
I saw "xxxxxx" too. How did you fix this？my import statement are:
```
import EasyMDE from 'easymde';
import 'easymde/src/css/easymde.css';
```
