### ISSUE TITLE
How to enable Insert Code toolbar command

### ISSUE THREAD

**Issue by w2know** [Ionaru/easy-markdown-editor#151]
**The **Insert Code** toolbar command is not enabled by default**
I am learning to take advantage of this useful editor.  However, I soon encounter this problem: how to enable the commands which are supported but not enabled by default.

Besides, what is the complete default configuration? 

Any help will be appreciated!

**Comment by Ionaru** [comment]
Check out the examples on https://easymde.tk/
The second editor has all the commands enabled.

**Comment by w2know** [comment]
> 
> 
> Check out the examples on https://easymde.tk/
> The third editor has all the commands enabled.

Thanks for pointing me to the example.  That solves my problem!
