### ISSUE TITLE
Focus the editor programmatically

### ISSUE THREAD

**Issue by Rukenshia** [Ionaru/easy-markdown-editor#156]
Hello,

I want to focus my editor through a keyboard shortcut. I used a simple textarea before and could just call myTextarea.focus() to switch focus. How does this work with this editor? It looks like everything is rendered as `div`s, so I'm not sure how I can achieve this.

Thanks!

**Comment by A-312** [comment]
```js
const easyMDE = new EasyMDE()
easyMDE.codemirror.focus()
```

**Comment by Rukenshia** [comment]
Worked like a charm, thank you!
