### ISSUE TITLE
Built-in spell-checker is cool, but I think it should be turned off by default.

### ISSUE THREAD

**Issue by StephenChips** [Ionaru/easy-markdown-editor#163]
Just a little suggestion. 

First of all, since the spell-checker is just a tool for checking english typo, but not other languages, it become useless when user writes in other language, because it cannot recognize them. Secondly, not every words are collected into the spell-checker's dictionary. For example, currenly the type-checker does not understand the word `Photoshop`. Lastly, I don't think we need a spell-checker 
at any time, since writing is not coding. Sometimes I just want to note something, and I do not care if there are any typos in my sentences.

**Comment by StephenChips** [comment]
I think spell-checking isn't an essential job to a editor, in contrast, recording markdown, translating it to html and displaying it properly on the preview is. In my opinion, the out-of-box features should only includes those essentials. If anyone wants more, he/she can add extra function via config.

**Comment by A-312** [comment]
Do you try `options.spellchecker: false` ?
