### ISSUE TITLE
Typing change to toolbar option is breaking existing code

### ISSUE THREAD

**Issue by FranklinWhale** [Ionaru/easy-markdown-editor#178]
**Describe the bug**
The typing change from `toolbar?: boolean | ReadonlyArray<string | ToolbarIcon>;` to `toolbar?: boolean | ReadonlyArray<'|' | ToolbarButton | ToolbarIcon | ToolbarDropdownIcon>;` in 2.10.0 breaks existing code that uses string array.

For example,

```ts
new EasyMDE({
	toolbar: [
		"bold",
		"italic",
		"heading",
		"|",
		"quote",
		"unordered-list",
		"ordered-list",
		"table",
		"|",
		"link"
	]
});
```

**Expected behavior**
The code should be compiled successfully.

**Version information**
- EasyMDE version: 2.10.0

**Comment by Ionaru** [comment]
Fixed in version 2.10.1
