### ISSUE TITLE
Fullscreen doesn't work with toolbar: false

### ISSUE THREAD

**Issue by aphitiel** [Ionaru/easy-markdown-editor#18]
1. Instantiate EasyMDE with `toolbar: false`
2. call  `toggleSideBySide` or `toggleFullscreen`
3. throws `TypeError: Cannot read property 'side-by-side'` of undefined [here](https://github.com/Ionaru/easy-markdown-editor/blob/23327bf21d1db810613191595cd0174d38d39a05/src/js/easymde.js#L735)

**Comment by Ionaru** [comment]
Fixed in #19
