### ISSUE TITLE
How to implement in Django Admin?

### ISSUE THREAD

**Issue by jaradc** [Ionaru/easy-markdown-editor#185]
Generally speaking, how would one implement EasyMDE in a Django admin textarea?

For example, I have a field named `content` in the admin panel of a post model.

`<textarea name="content" cols="40" rows="10" class="vLargeTextField" id="id_content"></textarea>`

I have the EasyMDE css and js files in another app "pages" so I'm referencing them from the "posts" app below:

```
@admin.register(Post)
class PostAdmin(admin.ModelAdmin):
    list_display = ('id', 'title', 'user')
    list_display_links = ('title',)
    #summernote_fields = ('content',)

    class Meta:
        model = Post

    class Media:
        css = {
            'all': ('pages/css/easymde.min.css',),
        }
        js = ('pages/js/easymde.min.js',)
```

In my posts/static/posts/js/custom.js, I have:

```
var easyMDE = new EasyMDE({element: document.getElementById('id_content')});
```

What am I missing?

**Comment by A-312** [comment]
`document.addEventListener('load'` ? does `id_content` exist?

**Comment by jaradc** [comment]
I guess the issue is that I didn't have my custom.js included in the js tuple.
```
    class Media:
        css = {
            'all': ('pages/css/easymde.min.css',),
        }
        js = (
            'pages/js/easymde.min.js',
            'posts/js/custom.js'
        )
```

I also did this:
