### ISSUE TITLE
Returning Rendered HTML

### ISSUE THREAD

**Issue by cryocaustik** [Ionaru/easy-markdown-editor#187]
Is it possible to return the result of the default converter (marked) to allow further usage of the the converted HTML code?

**Comment by cryocaustik** [comment]
looks like this can be done by calling the `previewRender()` function:

```js
let easymde = new EasyMeDE({ ... });

let converted = easymde.options.previewRender(easymde.value())
```
If this is a valid method, perhaps it could be added to the docs? I can submit a PR if you'd like.

**Comment by Ionaru** [comment]
It's even easier than that!

```js
let easymde = new EasyMeDE({ ... });
let converted = easymde.markdown(easymde.value());
```
