### ISSUE TITLE
forceSync not working?

### ISSUE THREAD

**Issue by spencertweedy** [Ionaru/easy-markdown-editor#197]
**Describe the bug**
forceSync doesn't store the EasyMDE editor's value in the original textarea.

**To Reproduce**
See this [Glitch](https://alkaline-wild-chili.glitch.me/).

**Comment by spencertweedy** [comment]
It appears that forceSync does immediately sync the EasyMDE content into the original textarea, but for some reason it doesn't fire any events on the original textarea.

I have a StimulusJS controller listening to "change" events on the original textarea and the change event isn't firing when EasyMDE syncs its contents into the textarea.

**Comment by n3storm** [comment]
Why is closed?

**Comment by hooopo** [comment]
@spencertweedy I had the same problem as you, how did you solve it?

**Comment by donv** [comment]
A workaround that works for me:

```
  new EasyMDE({
    element: ...,
    forceSync: true
  }).codemirror.on('change', (e) => {
    $(e.getTextArea()).trigger('change');
  });
```
