### ISSUE TITLE
Android Mobile Text Input 

### ISSUE THREAD

**Issue by BenediktGross1982** [Ionaru/easy-markdown-editor#20]
### I'm submitting a...
- [x] Bug report
- [ ] Feature request

### Reproduction steps
User a Android device and start typing. Each character is on a new line

### Version information
Browser type and version: Chrome, Firefox on Android
EasyMDE version: 2.1.0

**Comment by skylarmt** [comment]
It works fine for me on the latest version, tested in Firefox on Android and in an Android system webview.

**Comment by Ionaru** [comment]
Tested with android and the current latest editor version and it works as expected (Chrome on Android 8).
I'm going to consider this closed unless someone can reproduce this issue.
