### ISSUE TITLE
RTL Support for Easy Markdown Editor

### ISSUE THREAD

**Issue by seyzed** [Ionaru/easy-markdown-editor#202]
Hello,

I would like to request RTL support for Easy Markdown Editor. 
Please kindly add this feature as any Middle eastern cannot benefit from this great tool. 

Here is more information about RTL languages:
- https://en.wikipedia.org/wiki/Right-to-left
- https://www.w3.org/International/questions/qa-scripts.en

Usually two CSS classes are added to make anything RTL (depends on how complex the structure of the codes is):
```
direction: rtl;
text-align: right;
```

Thank you so much.

**Comment by Ionaru** [comment]
This is possible by setting the `direction` option on the exposed CodeMirror editor. For example:
```js
const easyMDE = new EasyMDE();
easyMDE.codemirror.setOption('direction', 'rtl');
```

The toolbar can also be aligned to the right edge by adding a CSS property.
```css
.editor-toolbar {
    direction: rtl;
}
```

**Comment by test-soulj-test** [comment]
> This is possible by setting the `direction` option on the exposed CodeMirror editor. For example:
> 
> ```js
> const easyMDE = new EasyMDE();
> easyMDE.codemirror.setOption('direction', 'rtl');
> ```

setOption does not work for me. 
I tried to see if codemirror.options changed with `easyMDE.codemirror.getOption('direction')` and I still get ltr.

**Comment by souljuse** [comment]
> This is possible by setting the `direction` option on the exposed CodeMirror editor. For example:
> 
> ```js
> const easyMDE = new EasyMDE();
> easyMDE.codemirror.setOption('direction', 'rtl');
> ```

setOption does not work for me. 
I tried to see if codemirror.options changed with `easyMDE.codemirror.getOption('direction')` and I still get ltr.
