### ISSUE TITLE
maxHeight affecting only preview size, not composition

### ISSUE THREAD

**Issue by mMerlin** [Ionaru/easy-markdown-editor#206]
**Describe the bug**

The maxHeight option is not putting a limit on the height of the composition area. Instead, it is limiting the height of the preview display area in side-by-side mode

**To Reproduce**

```html
    <textarea id="project_description"></textarea>
    <script>
      new EasyMDE({
        element: document.getElementById('project_description'),
        autoDownloadFontAwesome: false,
        autosave: {
          enabled: true,
          uniqueId: "EditProjectDescription",
          text: "Autosaved: "
        },
        uploadImage: true,
        showIcons: ["upload-image", "code"],
        hideIcons: ["image"],
        blockStyles:
          {
            code: "~~~"
          },
          maxHeight: "150px",
        sideBySideFullscreen: false,
      });
    </script>
```

**Expected behavior**

Setting maxHeight should set the editing area to the specified height. Side-by-side preview should use the full height of the composition area.

**Screenshots**

![easymde](https://user-images.githubusercontent.com/918823/84600603-bcab5200-ae37-11ea-9a18-b0957f9acdfa.png)

** Version information **
- OS: Fedora 31 workstation
- Browser: Firefox 77.0.1 (64-bit)
- EasyMDE version: commit 9dbb1db

**Comment by quinnzipse** [comment]
Here's a work around I use. I think might help your problem. I referenced the [SimpleMDE docs](https://github.com/sparksuite/simplemde-markdown-editor). @mMerlin
```
.CodeMirror {
            height: 85vh;
            overflow-y: auto;
        }
```

**Comment by nick-denry** [comment]
I guess it's because `minHeight` for the composition area is set to `300px` by default. `maxHeight` value set to `150px` is just too small and less than default `300px` value. You could try to set `minHeight` to `150px`, it's not ignored in this case.

**Comment by mMerlin** [comment]
That works. So the documentation needs to be updated. Currently says:

> **maxHeight:** Sets fixed height for the composition area. minHeight option will be ignored. Should be a string containing a valid CSS value like "500px". Defaults to undefined.

Obviously the minHeight is not being ignored. It needs to be equal or less than maxHeight. Which should probably be handed by the code.

**Comment by nick-denry** [comment]
> So the documentation needs to be updated.

Or `minHeight` option must be set equal to `maxHeight` always. I think pr needed.

@Ionaru ?
