### ISSUE TITLE
Add Ability to preview without full screen

### ISSUE THREAD

**Issue by CaptainYarb** [Ionaru/easy-markdown-editor#21]
### I'm submitting a...
- [ ] Bug report
- [x] Feature request

### Reproduction steps
The editor currently forces the user to go full screen with codemirror when the side by side mode is enabled. It would be nice to be able to disable this functionality as it's fairly opinionated by the original devs.

A quick option and if check [here](https://github.com/Ionaru/easy-markdown-editor/blob/master/src/js/easymde.js#L748) would resolve this.

**Comment by KingDarBoja** [comment]
Hi, any progress with this issue? It seems pretty old and it is still happening with latest version of the EasyMDE editor, even on the demo website.

**Comment by nick-denry** [comment]
Hi! I've created PR for this https://github.com/Ionaru/easy-markdown-editor/pull/196

PR adds an option `sideBySideFullscreen: (true|false)` with `true` by default (no default behavior changed).

The option set to `false` do the trick.

```js
var easyMDE = new EasyMDE({
     sideBySideFullscreen: false
});
```

**Comment by KjellMorgenstern** [comment]
@nick-denry Wouldn't it need the CSS changes to not look broken, and for the scrolling to work?

**Comment by nick-denry** [comment]
@KjellMorgenstern Yep, you're right. Miss the scrolling part cause of predefined external container. I'll do some extra tests.

**Comment by nick-denry** [comment]
So, a little PR update with demos.

The `sideBySideFullscreen: false` option keeps original editor behaviour to expand. Preview scrolling is the same as original editor scrolling via page scroll.

[Demo1: sideBySide with no fullscreen](http://www.denry.ru/mde-side-by-side-nofullscreen-expanded.html)

And as far as with the long text toolbar could not be visible, I've add a `maxHeight` option which allows to constraint editor height, so options could be used together (and it's need to be documented).

```js
maxHeight: '450px',
sideBySideFullscreen: false
```

[Demo2: sideBySide with no fullscreen and maxHeigth constraint](http://www.denry.ru/mde-side-by-side-nofullscreen-maxheight.html)

I've tested modes switch between `preview`, `sideBySide`, `fullscreen` and `fullscreen sideBySide`, but any help with tests wanted.
