### ISSUE TITLE
Add ability to pass `spellcheck` and `inputType` options to CodeMirror

### ISSUE THREAD

**Issue by Cherry** [Ionaru/easy-markdown-editor#22]
### I'm submitting a...
- Feature request

After adding
```javascript
inputStyle: "contenteditable",
spellcheck: true
```
to the CodeMirror initialisation at https://github.com/Ionaru/easy-markdown-editor/blob/master/src/js/easymde.js#L1584, I was able to get spellchecking within the browser (at least Google Chrome) functional without any apparent issues. If we could pass these options (or arbitrary options that just had defaults) to the CodeMirror initialisation, that would be awesome.

PS. Thanks so much for this fork of simplemde. It powers our internal CMS and our staff love using it.

**Comment by Cherry** [comment]
Any update on this? The built-in `spellChecker` is very limited and has many [outstanding issues](https://github.com/sparksuite/codemirror-spell-checker/issues). 

Being able to pass these options and enable the spellchecker built into the browser would be great, and would also help solve #78.

**Comment by Elmervc** [comment]
It would be nice if you can provide additional CodeMirror options to EasyMDE (but use with caution).

I also prefer to use the browser's spell check facility, so for now I manually added the OP mentioned options to the CodeMirror initialisation. It seems to work correctly (tested on Chrome and FireFox).

**Comment by A-312** [comment]
@Ionaru this one is fixed by #143
