### ISSUE TITLE
Can it be extended with markdown-it plugins?

### ISSUE THREAD

**Issue by ehhc** [Ionaru/easy-markdown-editor#220]
Hi there,
i would like to know whether, resp. how, the editor can be extended with existing markdown-it addons. I'm especially missing the following two features:
- Using tables (don't know why they don't work, but they aren't rendered in the demo)
- [Admonitions](https://www.npmjs.com/package/markdown-it-admonition)

Any Ideas how i can make them work? :)
Thanks :)

**Comment by clickwork-git** [comment]
>     * Using tables (don't know why they don't work, but they aren't rendered in the demo)
> 
>     * [Admonitions](https://www.npmjs.com/package/markdown-it-admonition)
> 
> 
> Any Ideas how i can make them work? :)
> Thanks :)

**Comment by clickwork-git** [comment]
>     * Using tables (don't know why they don't work, but they aren't rendered in the demo)

In the settings of the plugin EsayMDE you can add "table" to the field "Toolbar".

>     * [Admonitions](https://www.npmjs.com/package/markdown-it-admonition)

Here is the documentation of the editor EasyMDE:

https://github.com/Ionaru/easy-markdown-editor

**Comment by ehhc** [comment]
@Ionaru any ideas on this? :)

**Comment by Ionaru** [comment]
The default renderer can be competely overridden with the `previewRender` option. You can use any renderer instead of the default `marked` package.

**Comment by ehhc** [comment]
Thanks for your answer. So you mean, it's not a question of extending your editor, but about how to extend the marked library?

**Comment by Ionaru** [comment]
Yes, you can extend marked, but you can also just grab markdown-it, extend it with the plugins you want and use it in the `previewRender` function. :)

For example:
```js
const md = window.markdownit()
    .use(plugin1)
    .use(plugin2);

const easyMDE = new EasyMDE({
    previewRender: (text) => {
        return md.render(text)
    },
});
```

**Comment by ehhc** [comment]
Ah, thank you :) I'll try it :)
