### ISSUE TITLE
Cursor cannot be used correctly on start

### ISSUE THREAD

**Issue by djschilling** [Ionaru/easy-markdown-editor#221]
**Describe the bug**

When i load the editor with a value in it the cursor does not react correctly.
Only after i type a letter the cursor does react correctly.

**To Reproduce**

```
const editor = new EasyMDE({element: '#editor', initialValue: this.value});
```

I made a video to show the behaviour: https://seafile.church.tools/f/f5e70a36c13e49a38aad/
i tried to click some times in the video on the bottom of the text.

**Expected behavior**

The cursor should behave correctly when loading the editor with an initial value.

**Version information**

- OS: MacOS
- Browser: Chrome 84
- EasyMDE version: 2.11.0

**Comment by Ionaru** [comment]
Do you have the same behaviour on https://easymde.tk/ ?

**Comment by djschilling** [comment]
no i have not.

**Comment by djschilling** [comment]
we found out the problem was on our side.
