### ISSUE TITLE
Split mode should be available in non full screen

### ISSUE THREAD

**Issue by damodharanj** [Ionaru/easy-markdown-editor#233]
Split mode is available only in fullscreen. It should be available within the container too.

**Comment by nick-denry** [comment]
Duplicate of https://github.com/Ionaru/easy-markdown-editor/issues/21 ?

**Comment by nick-denry** [comment]
Try **sideBySideFullscreen** option. If set to `false`, allows side-by-side editing without going into fullscreen. Defaults to `true`.
