### ISSUE TITLE
Standard sideBySide enabled

### ISSUE THREAD

**Issue by rickerd** [Ionaru/easy-markdown-editor#236]
Maybe it's cool/nice to be able to initialize the MDE with the preview open.
That would be so great to me.

**Comment by Ionaru** [comment]
This is possible:
```js
const editor = new EasyMDE();
EasyMDE.togglePreview(editor);
```

**Comment by rickerd** [comment]
Yes this sure works great!
Maybe I was a bit wrong with the given information. I want the side by side open on start.
Is this also possible?
