### ISSUE TITLE
Prompt URLs option does not return and insert URL into editor

### ISSUE THREAD

**Issue by elixirgraphics** [Ionaru/easy-markdown-editor#238]
**Describe the bug**
So I'm running into a problem where I cannot seem to get Prompt URLs to work. The prompt appears and allows me to type the URL, but the URL is not returned and inserted into editor. I'm not sure if it is a bug or not. If you enable Prompt URLs, for Links and Images, are the URLs inserted after the prompt is closed? This is what happens for me: 

Video: https://d.pr/v/cRpfdV

**Expected behavior**
URL should be inserted into Link and Image Markdown.

**Comment by Ionaru** [comment]
Could not reproduce this on Windows using Chrome 85.0.4183.102.

It looks like you're using Safari with a customized editor. Can you confirm this issue with the default editor and just the `promptURLs` option turned on?

```js
var easyMDE = new EasyMDE({
    promptURLs: true
});
```

Also, next time please use the issue template and fill the version information.

**Comment by elixirgraphics** [comment]
Without the custom toolbar it seems to work. What is the trick for making it work properly with a custom toolbar?

**Comment by Ionaru** [comment]
```js
const easyMDE = new EasyMDE({
    toolbar: [
        'link',
        {
            name: 'link2',
            action: EasyMDE.drawLink,
            className: 'fa fab fa-link',
            title: 'Custom link',
        }
    ],
    promptURLs: true,
});
```

Even with a custom toolbar the link prompt works, can you share your editor setup?

**Comment by elixirgraphics** [comment]
Your help pointed me in the direction I needed... I had switched from SimpleMDE over to EasyMDE and still had the following section in my options:

```
insertTexts: {
    horizontalRule: ["", "\n\n-----\n\n"],
    image: ["![](https://", ")"],
    link: ["[", "](https://)"],
    table: ["", "| Column 1 | Column 2 | Column 3 |\n| -------- | -------- | -------- |\n| Text     | Text      | Text     |\n| Text     | Text      | Text     |\n\n"],
```

This was overwriting the returned URLs from the Prompts. Thanks for your help.
