### ISSUE TITLE
Hyperlink text getting doubled each time click on link

### ISSUE THREAD

**Issue by Gajendran7** [Ionaru/easy-markdown-editor#25]
### I'm submitting a...
- [x] Bug report
- [ ] Feature request

### Reproduction steps

1. Navigate to editor and enter some link
2. Select the link and click on link icon in header (multiple times)

### Version information
Browser type and version: Chrome (Desktop) - Latest version
EasyMDE version: NA
![2018-09-03_19-37-42](https://user-images.githubusercontent.com/17004190/44991205-fc7dae00-afb0-11e8-898b-d98815c8b745.gif)

**Comment by Ionaru** [comment]
The demo site uses the older SimpleMDE editor. Can you reproduce this with a more recent version?

(Still need to build a new demo website, sorry!)

**Comment by Jetski5822** [comment]
Yeah - it repros locally too using the latest editor here :(

**Comment by Ionaru** [comment]
Alright I've tracked down the issue, but what do you expect to happen when you click on the link button in this situation?

Should the link be removed or should nothing happen?

**Comment by danielok1993** [comment]
I have added toggling for links and images. I will submit pull request soon 👍

**Comment by nerg4l** [comment]
@danielok1993 Are you still planning to make a PR?

**Comment by danielok1993** [comment]
@nerg4l this was long ago, but I did make a PR. You can view it in the Pull Request section and copy what I have implemented, as my PR was not merged.

**Comment by nerg4l** [comment]
Thanks for the info @danielok1993, I found it #95
