### ISSUE TITLE
Make previewImagesInEditor false by default

### ISSUE THREAD

**Issue by dalboris** [Ionaru/easy-markdown-editor#251]
After upgrading to v2.12.0, I noticed that now images are shown in the editor. It was quite surprising to see such a big behavior change for a minor upgrade. I am using an unversioned CDN ("https://unpkg.com/easymde/dist/easymde.min.js"), so I didn't initiate the upgrade manually, and at first I thought there was some kind of bug. I toggled the edit/preview button multiple times, refreshed the page, until I finally investigated and found that the "issue" was caused by a new feature:

https://github.com/Ionaru/easy-markdown-editor/pull/235

While this is a potentially useful feature (thx @ivictbor  !), I really think this ought to be false by default. The first reason is obviously to be backward compatible with the previous behavior. The second reason is that even without backward compatibility concerns, I think showing the image in the editor kinda defeats the primary purpose of Markdown editing, which is to have precise control over the Markdown text to be sent to the server. When images are displayed, it makes editing harder and clunky. We cannot really be sure how many new lines or whitespaces there are before/after the image, and overall we lose some confidence about what's in the Markdown. I think that in most cases, if we want to see images, then a WYSYWYG editor makes more sense than a Markdown editor. It's subjective, obviously, but I feel that I may have not chosen easyMDE if in the demo page I had experienced this behavior, and not seen that it could be disabled.

Anyway, I've already personally turned it off, thanks a lot for making this possible! I just wanted to bring this to your attention, and perhaps start a discussion if others would like to argue for or against having it to false by default.

**Comment by ivictbor** [comment]
@dalboris @Ionaru Yep, agree, I think we need to set false (at least for now), I also noted several minor issues, e.g. when image is posted in inline string

**Comment by Ionaru** [comment]
Released in 2.12.1
