### ISSUE TITLE
CodeMirror CSS should be scoped to EasyMDE

### ISSUE THREAD

**Issue by infime** [Ionaru/easy-markdown-editor#252]
**Describe the bug**

Some CSS selectors (specifically .CodeMirror) are too broad and affect other instances of CodeMirror in an application.

**To Reproduce**

Import EasyMDE CSS into an app that is already using CodeMirror. Other instances of CodeMirror will have styles intended specifically for EasyMDE applied.

**Expected behavior**

EasyMDE CSS to only affect it's instance(s) of CodeMirror.

I'd be happy to get this going in a PR.

**Comment by Ionaru** [comment]
I've added extra scoping to the CSS, please try the `@next` version to see if that solves your issues.

**Comment by infime** [comment]
@Ionaru works great, thanks!
