### ISSUE TITLE
Support for emojis?

### ISSUE THREAD

**Issue by qaler** [Ionaru/easy-markdown-editor#256]
**Is your feature request related to a problem? Please describe.**
Emojis are helpful in today's emotion expression.

**Describe the solution you'd like**
Can easy markdown editor support markdown emoji display/rendering (pure text to image) on preview mode?

**Comment by Ionaru** [comment]
Related: https://github.com/markedjs/marked/issues/233
You can extend (or overwrite) the markdown parser, [this comment](https://github.com/markedjs/marked/issues/233#issuecomment-323943368) has the relevant code.

Of course you can also use emoji by using your OS' emoji picker (on Windows: <kbd>Win</kbd> + <kbd>.</kbd>). This already works in the editor.

**Comment by qaler** [comment]
Many thanks to your reply!

**Comment by Zignature** [comment]
I was able to incorporate emoji shorthand parsing e.g. turning `:heart:` into :heart:

How would I go about separating this from the core code? Adding it as an extension in a separate file.

**Comment by Ionaru** [comment]
I don't think we need built-in emoji "support" in the editor. Regular unicode emoji can be used through emoji-keyboards which are standard on pretty much every OS and device.

**Comment by Zignature** [comment]
True.

I'm creating a Markdown editor fieldtype add-on for [ExpressionEngine CMS](https://expressionengine.com/) where I'd like to have it :)

Typing shortcodes that will render in the preview. Shortcodes will be saved to the database instead of unicode strings.
That's why I'd like to separate it from the core. Makes for easier maintenance.

**Comment by Zignature** [comment]
Personally, on a mobile device I'd use the emoji keyboard On a PC I'd rather enter emojis with shortcodes. I will also try to include an "emoji autocomplete" box, just like on GitHub.

**Comment by Zignature** [comment]
I understand we'll have to wait for a stable CM6 for separation
