### ISSUE TITLE
Content fails to load when element isn't yet in the DOM on page load

### ISSUE THREAD

**Issue by Canuckaholic** [Ionaru/easy-markdown-editor#260]
**Describe the bug**
Related to https://github.com/codemirror/CodeMirror/issues/2469

When a screen of my web app first loads, the easyMDE text area component isn't yet in the DOM. When it is loaded, there is content that I'm expecting to appear in the easyMDE text area from setting its value (easyMDE.value('value'), however it doesn't appear until I click into the field.

**Comment by Ionaru** [comment]
#249 might resolve this.
