### ISSUE TITLE
How do I use this with accessible html forms

### ISSUE THREAD

**Issue by charliematters** [Ionaru/easy-markdown-editor#261]
I'm using this (via `react-simplemde-editor`) and I'm struggling to get it to focus correctly in a form.

I have tried:
* A label with the appropriate `for` attribute which matches the id on the `<textarea>` used
* Focussing the editor programmatically with something like `getElementById('markdown-input').focus()`
* Using the aria attributes `aria-labellledby` and giving it the ID of the label

I'm not sure how to continue, as codemirror (<6) is using a lot of divs to reproduce the standard html components.

Second, related question: Can I disable the editor handling the `Tab` key? Currently I can't move to any of the subsequent form controls using the keyboard

**Comment by Ionaru** [comment]
You can focus the editable area by calling `editor.codemirror.focus();`.

At this moment there is no built-in option to disable the <kbd>Tab</kbd> key. This is assigned here: https://github.com/Ionaru/easy-markdown-editor/blob/6d173d0024dc86974ac1d0aa4baae108cc096867/src/js/easymde.js#L1972

But you might be able to do something with the `addKeyMap` or `removeKeyMap` functions from codemirror.

**Comment by charliematters** [comment]
Thanks for this - this solved my issue.

I managed to use `removeKeyMap` function to stop the editor acting on the `Tab` presses, but I couldn't get it to bubble that event up to the browser again. It's not my best work, but for anyone coming across this in the future, I ended up with this:

In my MarkdownInput.tsx file (which is where I'm rendering the `react-simplemde-editor`), I updated the keypress handler
```typescript
 const handleKeyDown = React.useCallback(
    (instance: CodeMirror.Editor, event: KeyboardEvent) => {
      if (event.key === 'Enter' && event.ctrlKey) {
        onCtrlEnter()
      }
      if (event.key === 'Tab') {
        // Stop CM handling the Tab
        event.preventDefault()
        // Tell the parent we have tabbed so that we can focus the next element
        onTab()
      }
    },
    [onCtrlEnter, onTab]
  )
```

And in the parent React component:
```typescript
  <MarkdownInput 
    ...
    onTab={() => {
      // Not pretty, but it allows the next field to handle the events in the default way
      document.getElementById('next-control-label').click()
    }}
  />
```

Like I say in the comments, it's not idiomatic React code, but it does allow users with assistive tools to Tab into and out of the control
