### ISSUE TITLE
Plain text links are clickable in Preview

### ISSUE THREAD

**Issue by cjmaxik** [Ionaru/easy-markdown-editor#264]
**Describe the bug**
When you paste URL (or write it by hand) in Editor, it will be clickable in Preview, but it is not wrapped in Markdown code, so it should be plain text.

**To Reproduce**
1. Paste link in the editor
2. Click on 'Preview'
3. Hover on the link in Preview
4. See that link is clickable
5. Check the original text area (with `forceSync`)
6. Link will be in plain text

**Expected behavior**
1. Link should be in plain text (not clickable) in Preview
or
2. Link should be automatically wrapped with `[](https://*)` in Editor
or
3. Have an option to disable this behavior

**Screenshots**
![image](https://user-images.githubusercontent.com/1501705/97870891-ad646c80-1d24-11eb-90f3-2e2610f5610f.png)

** Version information **
- OS: Windows
- Browser: Chrome v88
- EasyMDE version: 2.12.1

**Comment by nhymxu** [comment]
I think problem from marked.js
https://github.com/markedjs/marked/issues/882

Customize this is very complex. So just edit your code and self compile is better
