### ISSUE TITLE
Spell check not working

### ISSUE THREAD

**Issue by Fanvadar** [Ionaru/easy-markdown-editor#276]
**Describe the bug**
I can't seem to get any type of spell checking to work regardless of what configs I provide. 

**To Reproduce**
1. Create a bare basic easyMDE: 
    `var easyMDE = new EasyMDE({element: document.getElementById('my-text-area'), spellChecker: true});`
2. This does not provide spell checking for me
3. Even on all of the [demos](https://easymde.tk/) there is no spellchecking, even though it says spellChecker defaults to true.

**Expected behavior**
Spellchecking

** Version information **
- OS: Windows
- Browser: Chrome
- EasyMDE version: 2.13.0

**Comment by Jezdufourq** [comment]
I have been meaning to see this fixed! Nice find.

**Comment by Ionaru** [comment]
This used to work a few releases ago, if someone can pinpoint when it broke then a fix should be easy.

**Comment by Fanvadar** [comment]
@Ionaru This bug was introduced in version 2.12.0 (2.11.0 works, 2.12.0 doesn't).
