### ISSUE TITLE
`cleanup` throws an error

### ISSUE THREAD

**Issue by emirotin** [Ionaru/easy-markdown-editor#278]
**Describe the bug**

**To Reproduce**
1. Create a new instance
2. Call `cleanup` on it
4. See the error in the console

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/525832/102791134-3e63d580-43af-11eb-997c-b65b1ed559f1.png)

**Additional context**
The reason is this line: `window.removeEventListener(this.onWindowResize);` which is missing the even name (`resize`) as the 1st argument

**Comment by Ionaru** [comment]
I think this was caused by #253, the `removeEventListener` call might not be needed anymore since that change.

**Comment by emirotin** [comment]
Well, it looks like the issue was there for quite some time before this change but it was masked by the fact that `this.onWindowResize.toString()` evaluated to `[Function]` which is of course not a valid event name but didn't cause the exception.

**Comment by emirotin** [comment]
PRed the fix: https://github.com/Ionaru/easy-markdown-editor/pull/280
