### ISSUE TITLE
Blockquote double enter not removing stay >

### ISSUE THREAD

**Issue by Jetski5822** [Ionaru/easy-markdown-editor#28]
### I'm submitting a...
- [x] Bug report
- [ ] Feature request

### Reproduction steps
When doing a block quote, i hit enter twice, I expect the last one to disappear i.e.

```
> fubar
>
qqeqweqw
```
You end up with a stray >

Lists work fine, just blockquote

**Comment by Ionaru** [comment]
This behaviour is intended.

It's part of the `continuelist` plugin of CodeMirror and mentioned in issue https://github.com/codemirror/CodeMirror/issues/4526.
