### ISSUE TITLE
Broken demo link in readme.md

### ISSUE THREAD

**Issue by duncanwerner** [Ionaru/easy-markdown-editor#283]
Your readme points to `https://easymde.tk/`, maybe an old domain? 

Editor is great, it just took me a moment to find the right link to the demo.

**Comment by Ionaru** [comment]
Good catch. The `https://easymde.tk/` domain was a free one and it expired a few days ago (thanks Freenom for sending reminder... /s). So now I'd have to "buy" it back... Instead I claimed a new one.
I'll update the README.
