### ISSUE TITLE
sideBySideFullscreen: false > Uncaught TypeError: Cannot read property 'className' of undefined

### ISSUE THREAD

**Issue by Offerel** [Ionaru/easy-markdown-editor#289]
If i set sideBySideFullscreen: false and i click the side-by-side icon, i get a error message:
`Uncaught TypeError: e is undefined`

```
var mde = new EasyMDE({
			element: document.getElementById('md'),
			autoDownloadFontAwesome: false,
			spellChecker: false,
			autofocus: true,
			status: false,
			promptURLs: true,
			sideBySideFullscreen: false,
```
- load the editor in a browser
- Click the side-by-side button
- in JS console `Uncaught TypeError: e is undefined` is displayed

**Expected behavior**
SideBySide view is opened not in fullscreen

**Screenshots**
![grafik](https://user-images.githubusercontent.com/14041522/105370622-0c3ed100-5c04-11eb-83e3-8fda52a8f671.png)

** Version information **
- Browser: Firefox 84.0.2
- EasyMDE version: 2.13.0

**Comment by Offerel** [comment]
The error message has now changed (at least in Chrome) to `Uncaught TypeError: Cannot read property 'className' of undefined`

**Comment by elixirgraphics** [comment]
I too have recently come across this. Seems to happen for me when I have more than one instance of EasyMDE on the page.

**Comment by Offerel** [comment]
In EasyMDE version: 2.14.0 the issue is solved. Many thx.
