### ISSUE TITLE
Apply toolbar top and bottom spacing using padding?

### ISSUE THREAD

**Issue by sn3p** [Ionaru/easy-markdown-editor#292]
### Questions(s)

Is there any particular reason the top and bottom spacing inside the toolbar is done using `:before` and `:after`?

https://github.com/Ionaru/easy-markdown-editor/blob/0ff81e89a6ee37272ddfbcdf5084d6c961dc1669/src/css/easymde.css#L74-L87

And why the left and right spacing is added using `padding`?

https://github.com/Ionaru/easy-markdown-editor/blob/0ff81e89a6ee37272ddfbcdf5084d6c961dc1669/src/css/easymde.css#L66

### Proposal

Would it make sense to just set the spacing using padding, and remove the :before and :after "hack"?

```css
padding: 9px 10px;
```

This would make it easier to customize.
Can make a PR but pitching this first :)

**Comment by Ionaru** [comment]
I'm not sure why this is done. The commit that introduced it is from waaaaaaaay before I made this fork: https://github.com/Ionaru/easy-markdown-editor/commit/de7f1a8d118a90f584727571d18b8b699fa1cc98.
Feel free to make a PR for it :)

**Comment by sn3p** [comment]
PR created #293
