### ISSUE TITLE
Editing without viewing the markdown ?

### ISSUE THREAD

**Issue by stuaxo** [Ionaru/easy-markdown-editor#3]
It would be great to have a mode, like preview - but with editing.

Some of my users are non-technical, so I could show them a version of the editor that doesn't have the markdown available.

**Comment by Ionaru** [comment]
At the moment this would be really difficult to implement and somewhat out-of-scope of what I want to do with this fork in the near future. But it is a good suggestion and I'll keep it in mind.

**Comment by stuaxo** [comment]
Any idea what would need to be done?

**Comment by Ionaru** [comment]
The editor would somehow have to display the rendered markdown over the editor, while still maintaining the ability to select, copy/paste and edit text.

Markdown isn't very difficult to learn and the toolbar is there for the less-technical users.
