### ISSUE TITLE
Publish releases as compiled binaries

### ISSUE THREAD

**Issue by NicoHood** [Ionaru/easy-markdown-editor#303]
Heyho!
I was searching for compiled binaries, but I could not find them in this github repo (`dist`) or in hte [Github Releases](https://github.com/Ionaru/easy-markdown-editor/releases). I've simply downloaded them from the unpkg mirror, but it would be nice, if they can be provided here.

What do you think?

**Comment by Ionaru** [comment]
I would rather not do that. There's way to download them using unpkg or npm directly, I don't see the benefit of providing them here.

(Also it would require some changes in the CI/CD pipeline or manual work each release.)

**Comment by NicoHood** [comment]
Alright, your choice ;-)
