### ISSUE TITLE
Codemirror v6

### ISSUE THREAD

**Issue by affvalente** [Ionaru/easy-markdown-editor#324]
Hi,

Are there plans to integrate Codemirror v6? 

https://codemirror.net/6/

Thanks

**Comment by Ionaru** [comment]
Once codemirror 6 has a stable version and the addons we need are updated/compatible as well, then we'll upgrade.
I actually wanted to combine the upgrade with a switch to Typescript. :)

**Comment by affvalente** [comment]
Thanks! And just to confirm there's no way currently to enable iOS spellcheck, text replacement etc?

**Comment by Ionaru** [comment]
There's a few open issues for that: #23 and #113, but because I don't own any iOS devices I have no way to test any potential fixes and have to rely on other developers to do it.
