### ISSUE TITLE
PlantUML, DITAA and similar ASCII to image plugins

### ISSUE THREAD

**Issue by paulvi** [Ionaru/easy-markdown-editor#35]
Does EME support PlantUML or DITA (or how to add support)?
1. http://plantuml.com/sequence-diagram
2. https://github.com/stathissideris/ditaa

**Comment by Ionaru** [comment]
This would require significant modifications to CodeMirror and the rendering of the markdown preview.
In its current version the editor only handles pure Markdown, and nothing more.

This feature is out of scope of this project.
