### ISSUE TITLE
Please include dist build in releases

### ISSUE THREAD

**Issue by BrianGilbert** [Ionaru/easy-markdown-editor#350]
**Is your feature request related to a problem? Please describe.**
I would like to use this project as a library within my Drupal projects ([https://www.drupal.org/](https://www.drupal.org)).

I am upgrading an existing contrib module that uses a very old version of SimpleMDE, SimpleMDE used to create releases with a dist folder included, would it be possible to do the same please?

**Describe the solution you'd like**
built dist release included in release archives

**Describe alternatives you've considered**
There is not really any tooling option available that would exist on all hosting platforms to generate this at build time with a php based project.

**Additional context**
N/A

**Comment by Ionaru** [comment]
The release archives (uploaded to npm) do contain the dist folder with bundled and minified files, but they are not uploaded to Github.

If you just want to download the dist files, you can get them here:
https://unpkg.com/easymde@latest/dist/easymde.min.js
https://unpkg.com/easymde@latest/dist/easymde.min.css

**Comment by BrianGilbert** [comment]
oh, thanks, how can I get the link for the archive zip for 2.15.0? I need the zip so that I can use composer to pull it in.

**Comment by Ionaru** [comment]
If you have access to npm commands I'd recommend using `npm pack easymde`. This will download a compressed version of the release archive.

Alternatively you can access the npm registry directly with this link: https://registry.npmjs.org/easymde/latest
You'll find the download link under the `dist` key: https://registry.npmjs.org/easymde/-/easymde-2.15.0.tgz

**Comment by BrianGilbert** [comment]
can work with tgz, thanks!
