### ISSUE TITLE
Submenu actions not working in Chromium Browsers

### ISSUE THREAD

**Issue by Offerel** [Ionaru/easy-markdown-editor#362]
**Describe the bug**
If an action is assigned to a button in an submenu, this action is not called, when the button is clicked.

**To Reproduce**
1. Define a submenu, for example:
```
{
  name: 'FileMenu',
  className: 'ma ma-file',
  title: 'File',
  children: [
    {
      name: 'Save',
      action: saveFile,
      className: 'ma ma-save',
      title: 'Save'
    },
    {
      name: 'New',
      action: newFile,
      className: 'ma ma-new',
      title: 'New'
    }
  ]
},...
```
2. Define a function newFile, for example:
```
function newFile() {
  console.log("test");
}
```
3. Load the example and click on File > New
4. Check the browser console
5. No output on console is shown in Google Chrome, Chromium, Edge or similar browser. It is working however in Firefox.

**Expected behavior**
In Broser console the output "test"

** Version information **
- OS: Windows 10
- Browser: Chrome 95, Chromium 95, Edge 95
- EasyMDE version: 2.15.0

**Comment by halanikkola** [comment]
Hi! Just noticed this discussion after spotting the same issue. Seems that Chrome works with this solution. The solution persists with Safari. Seems that the button content in `.easymde-dropdown` requires a tabindex value. Is there a PR or a discussion on this I've missed`

**Comment by vazsonyidl** [comment]
Any update on this? When will 2.16.0 version be released?

**Comment by Ionaru** [comment]
@halanikkola @vazsonyidl 

What would need to be added or changed to fix this problem on safari and the browser @vazsonyidl tested with?

**Comment by halanikkola** [comment]
@lonaru The dropdown buttons `.easymde-dropdown` has an `i` element inside for the icon. The `i` needs` a `tabIndex` attribute (I guess value -1) and some styles to remove the blue focus ring from the icon. After this, the `:focus-within` pseudo-selector seems to work on Safari too.

**Comment by kelvinj** [comment]
@Ionaru it appears Safari does not treat the `<button>` element as focusable.

So, for example if I tweak the `createToolbarDropdown` function, changing:

`var el = createToolbarButton(options, false, enableTooltips, shortcuts, 'button', parent);`

to 

`var el = createToolbarButton(options, false, enableTooltips, shortcuts, 'div', parent);`

… then it seems to work in Safari (although the presentation is a little off.

**Comment by Ionaru** [comment]
@kelvinj and with the suggestion @halanikkola did (adding `tabIndex` to the  `<i>` element inside the button, does the toolbar then work as expected in Safari?

**Comment by kelvinj** [comment]
@Ionaru no, that didn't work.

FYI [this whatwg article](https://blog.whatwg.org/focusing-on-focus) mentions how Safari treats non-editable form elements as "not click focusable by default", which is what is causing the problem on this.

I have been doing a bit of testing, and it seems that you can make `<button>` elements on Safari focussable, by providing an `onclick()` event. But, this then means you have to manage a little bit how the `blur` takes place, to avoid the dropdown becoming sticky.

I changed the `createToolbarDropdown` function (see below), which got the dropdown working across FF, Chrome and Safari on the Mac, but I don't have deep enough knowledge of how this is used to know if this would cause other issues:

```js
/**
 * Create dropdown block
 */
function createToolbarDropdown(options, enableTooltips, shortcuts, parent) {
    var el = createToolbarButton(options, false, enableTooltips, shortcuts, 'button', parent);
    el.className += ' easymde-dropdown';

    el.onclick = function () {
        el.focus();
    };

    el.onblur = function () {
        parent.codemirror.focus();
    };

    var content = document.createElement('div');
    content.className = 'easymde-dropdown-content';
    for (var childrenIndex = 0; childrenIndex < options.children.length; childrenIndex++) {

        var child = options.children[childrenIndex];
        var childElement;

        if (typeof child === 'string' && child in toolbarBuiltInButtons) {
            childElement = createToolbarButton(toolbarBuiltInButtons[child], true, enableTooltips, shortcuts, 'button', parent);
        } else {
            childElement = createToolbarButton(child, true, enableTooltips, shortcuts, 'button', parent);
        }

        childElement.addEventListener('click', function (e) { e.stopPropagation(); }, false);

        content.appendChild(childElement);
    }
    el.appendChild(content);
    return el;
}
```

Sorry this is not in the form of a PR, but I don't have the repo set up as it stands, I've just been editing in a project that depends on `EasyMDE`. 

Thanks for the work, HTH.

**Comment by Ionaru** [comment]
Apologies for the late reply.

I've tested your code, @kelvinj, but with the `el.onblur` enabled the dropdown becomes very sticky, it will not always close when I click somewhere else.

I've pushed your suggestion without the `el.onblur` to version `2.15.1-21.0`, does that work?

**Comment by Ionaru** [comment]
From what I have been able to test using Browserstack, the submenu works in Safari, however the menu does not stay open after clicking an option, which I think is acceptable.

https://easy-markdown-editor.tk/ now shows an editor with a dropdown menu at the bottom of the page.

**Comment by kelvinj** [comment]
I have tested `2.15.1-21.0` and I think that is acceptable behaviour.

It means in my custom actions, I need to call `editor.codemirror.focus();` and this gives a more natural experience, since I want the editor to maintain its focus.

Thanks @Ionaru
