### ISSUE TITLE
Tag is missing: 2.16.0

### ISSUE THREAD

**Issue by ThomasRitter75** [Ionaru/easy-markdown-editor#367]
When adding the tag for 2.16.0, @Ionaru mistyped and wrote 2.6.0. 
This is visible in the tags switcher, where 2.6.0 is above 2.16.0 and there is another 2.6.0 down below 2.7.0
Because of that, the version 2.16.0 is not on NPM.

**Comment by ThomasRitter75** [comment]
Or did I misunderstand the changelog and that version is not released yet?

**Comment by Ionaru** [comment]
That version is not released yet. There's still some issues with https://github.com/Ionaru/easy-markdown-editor/issues/362 in Safari browsers.

**Comment by ThomasRitter75** [comment]
Understood. I checked the fix for the chrome issue and just added that CSS to my application.
