### ISSUE TITLE
IE11 - mouse slection not working

### ISSUE THREAD

**Issue by working-name** [Ionaru/easy-markdown-editor#37]
### I'm submitting a...
- [x] Bug report
- [ ] Feature request

### Reproduction steps
1. Open browser. 
2. Type several paragraphs. 
3. Try selecting one of the paragraphs in IE11. 
4. Kick yourself in the nutsack.
5. Load up https://simplemde.com/ in the same browser
6. Successfully select any paragraph you want.
7. Kick yourself in the nutsack.
8. Ponder what may have introduced this odd bug.

https://jsfiddle.net/vo1g3kue/

### Version information
Browser type and version: IE 11.471.17134.0
EasyMDE version: any?

**Comment by Ionaru** [comment]
Thank you for the report.

I suspect this has something to do with the newer version of CodeMirror that is used with EasyMDE.
If at all possible, switch to a more modern browser.

I'll investigate and see if I can get this working again, but to be honest with you it won't be a real priority.

**Comment by working-name** [comment]
I know, IE11... who uses that OtherBrowser Downloader™ as an actual browser? Apparently corporate sys admins think IE11 is the only browser invented since the 80s. Yay 😐

It's not CodeMirror, I checked. My uneducated/non-developer guess is that there's some weird listener on mouse drags or on selections that trigger and IE11 halts the selection at that point.

```js
mp:vanilla-simplemde macpro$ npm list | grep codemirror
+-- codemirror@5.42.0
```

```js
mp:vanilla-easymarkdown macpro$ npm list | grep codemirror
+-- codemirror@5.41.0
+-- codemirror-spell-checker@1.1.2
```

**Comment by working-name** [comment]
Uh... I take that back, it is CM, specifically `styleSelectedText`. Setting that to false will let IE do its thing.

**Comment by Ionaru** [comment]
Since that is an option provided by EasyMDE, can I consider this issue solved?

```js
new EasyMDE({
    styleSelectedText: false
});
```

**Comment by working-name** [comment]
Absolutely. If at some point in the future you have the time to look into what that function does, it would be awesome if you shared that with me. I can’t figure out what exactly it does. 

Thanks!

**Comment by Ionaru** [comment]
It instructs CodeMirror to give selected text the `CodeMirror-selectedtext` class, allowing for easy styling of the selected text.
EasyMDE currently does not use this in its default style.
