### ISSUE TITLE
open SimpleMDE vulnerability  issues

### ISSUE THREAD

**Issue by buttle** [Ionaru/easy-markdown-editor#370]
Hi,

Thanks for keeping this project alive!

I've seen on the original SimpleMDE repository that there are various [open vulnerability  issues](https://github.com/sparksuite/simplemde-markdown-editor/issues?q=is%3Aissue+is%3Aopen+vulnerability)

My question: Have these been fixed? Or, what is their status?

Cheers.

**Comment by wdebusschere** [comment]
https://snyk.io/test/npm/easymde/2.11.1-373.0

**Comment by Ionaru** [comment]
Vulnerabilities in the code or in the dependencies have all been fixed. 

However the often-reported XSS vulnerability / sanitizing input is not something I believe should be handled by the editor, but by the developers using EasyMDE on their websites. Either by using the option from `marked` or processing the input before it is passed to the editor.

**Comment by buttle** [comment]
Thank you very much!
