### ISSUE TITLE
problems in urls with special characters

### ISSUE THREAD

**Issue by Sonia-pl** [Ionaru/easy-markdown-editor#373]
When the user writtes in the editor some urls with parameters like this: ?$filter=parentmasteragent=%JCL% this url is not saved.
We cannot control if the url writted by the user is correct. Can you correct this point?

Besides, when the user writes in the editor urls with '(' , ')' characters, we get a 404 , but if we access from navigator the url
works correctly.

Thanks

**Comment by Zignature** [comment]
I just tried some test links and they all work fine for me:

1. Test link  with [special characters](http://example.com/?$filter=parentmasteragent=%JCL%) -> http://example.com/?$filter=parentmasteragent=%JCL%
2. Test link with [parentheses](http://example.com/?caniuse=(parentheses)) -> http://example.com/?caniuse=(parentheses)
3. Test link with [parentheses & special characters](http://example.com/?$filter=(parentmasteragent)=%JCL%) -> http://example.com/?$filter=(parentmasteragent)=%JCL%

My best guess is that your CMS is sanitizing user input and removing or replacing characters in the links.

**Comment by Sonia-pl** [comment]
1) Yes, I agree with you if we remove satinaze option point number one works.
2) The problem with http://example.com/?caniuse=(parentheses) is that the last ) is removed, and this url works without ), and our url does not work without it.

**Comment by Zignature** [comment]
I think you have "unbalanced" parentheses in your links, meaning no opening or closing parenthesis. This messes up the rendered link:

- [Link no parens](http://example.com?parens=absent) -> `http://example.com?parens=absent`
- [Link with balanced parens](http://example.com?parens=(balanced)) -> `http://example.com?parens=(balanced)`
- [Link with unbalanced parens](http://example.com?parens=unbalanced)) -> `http://example.com?parens=unbalanced)`
- [Link with unbalanced parens](http://example.com?parens=(unbalanced) -> `http://example.com?parens=(unbalanced`

**Comment by Zignature** [comment]
Links with unbalanced parentheses or unbalanced square brackets _will_ work if you enter them between `<` and `>` characters:

- <http://example.com?parens=unbalanced)> -> `<http://example.com?parens=unbalanced)>`
- <http://example.com?parens=(unbalanced> -> `<http://example.com?parens=(unbalanced>`

**Comment by Zignature** [comment]
The parentheses and pointy/angle brackets can also be escaped with a backslash.

**Comment by Zignature** [comment]
Links could be escaped if entered with the JS prompt (_option_ `promptURLs` _needs to be set to_ `true`).
The same applies to image links.

```
/**
 * Action for drawing a link.
 */
function drawLink(editor) {
    var cm = editor.codemirror;
    var stat = getState(cm);
    var options = editor.options;
    var url = 'https://';
    if (options.promptURLs) {
        url = prompt(options.promptTexts.link, 'https://');
        if (!url) {
            return false;
        }

        if (/[()<>]/.test(url)) url = escapeUrl(url);
    }
    _replaceSelection(cm, stat.link, options.insertTexts.link, url);
}

/**
 * Escape URLs to prevent breaking up rendered Markdown links
 * @param url {string} The url of the link or image
 */
function escapeUrl(url) {

    url = url.replace(/\(/g,'\\(')
             .replace(/\)/g,'\\)')
             .replace(/</g,'\\<')
             .replace(/>/g,'\\>');

    return url;
}
```

Good idea @Ionaru ?
By the way, I tried looping over an object but that didn't work out, hence the consecutive replaces.

Ofcourse people cannot be stopped entering URLs manually and forgetting to escape them, and the problem with unbalanced square brackets in the link text remains...

**Comment by Zignature** [comment]
The first of the above two commits can be skipped/omitted.

**Comment by Ionaru** [comment]
I'm not sure if escaping is the right call here, sorry for the late reply.
Maybe we should encode them instead? https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/encodeURI

**Comment by Zignature** [comment]
Been thinking about that too but the question is whether encoded parentheses (`%28` and `%29`) and angle brackets (`%3C` and `%3E`) are accepted/recognized by the CMS it's send to.

Only parentheses and angle brackets mess up link rendering., but it's just as simple a fix as escaping :)
Simpler yet because no extra function is needed.

`if (/[()<>]/.test(url)) url = encodeURI(url);`

**Comment by Zignature** [comment]
Or create a new `option` where people can choose:
- Keep the URL as is
- Encode the URL
- Escape the URL

`transformURL: "encode|escape"`

**Comment by Zignature** [comment]
Parentheses aren't encoded... so the problem remains when encoding URLs

**Comment by Zignature** [comment]
Or do both. First encoding and then escaping if parentheses are present: 
```
url = encodeURI(url);
if (/[()]/.test(url)) url = escapeURI(url);

...

function escapeURI(url) {

    url = url.replace(/\(/g,'\\(').replace(/\)/g,'\\)');

    return url;
}
```

**Comment by Ionaru** [comment]
The last suggestion sounds good.

**Comment by Zignature** [comment]
optional or automatic?

**Comment by Ionaru** [comment]
Automatic, I think an option is overkill.

**Comment by Zignature** [comment]
Just did a PR #393
