### ISSUE TITLE
Is this project actively maintained?

### ISSUE THREAD

**Issue by artknight** [Ionaru/easy-markdown-editor#377]
Hi,
I am an active user of this lib. Over the past year I have posted a few bugs and provided several solutions to issues. However, no one seems to be responding/ acknowledging those, let alone implementing them. 

**So my question is whether or not this project is being actively maintained?** 

Please respond =)

**Comment by Ionaru** [comment]
Same answer as https://github.com/Ionaru/easy-markdown-editor/issues/355.

**Comment by Ionaru** [comment]
Closing this as I think the question has been answered.
