### ISSUE TITLE
Examples don't work

### ISSUE THREAD

**Issue by erossini** [Ionaru/easy-markdown-editor#378]
I try to run the examples but they don't work. First, the path in the `link` and `script` is not correct. This is the working `index.html`

```
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Example / Preview</title>
    <link rel="stylesheet" href="../src/css/easymde.css">
    <script src="../src/js/easymde.js"></script>
</head>

<body>
    <textarea></textarea>
    <script>
        const easyMDE = new EasyMDE();
    </script>
</body>

</html>
```

Then, the other issues are:
- first line in the `easymde.js`, `require` is not defined
- line 1802: this.render is not a function

If I use the distribution, the upload of an image seems not working.

**Comment by Ionaru** [comment]
You have modified the script path, that is why the editor is not working. It should be `../dist/easymde.min.js`. You can **not** use `src/js/easymde.js` in a browser.

Image uploading requires a working server to receive the image, set with `imageUploadEndpoint`. Look in the [README.md](https://github.com/Ionaru/easy-markdown-editor/blob/master/README.md) for more info.

**Comment by erossini** [comment]
Ok, thank you for the answer. I'm not an expert in JavaScript but I was trying to debug the script to find a way to have the dropped file. I opened another [question](https://github.com/Ionaru/easy-markdown-editor/issues/379) with all the details.

**Comment by erossini** [comment]
Oh, I opened 2 questions :)
[This](https://github.com/Ionaru/easy-markdown-editor/issues/376) is a similar one.
