### ISSUE TITLE
Line number in status bar has offset [Fixed]

### ISSUE THREAD

**Issue by Zignature** [Ionaru/easy-markdown-editor#381]
**Describe the bug**
The cursor position in the status bar (line:column) is wrong. The line number has an offset of -1.

**To Reproduce**
Position the cursor anywhere in the document and check the line number in the status bar.

**Expected behavior**
I expect the line number to be correct.

**Screenshots**
Current:
![cursor-position-wrong](https://user-images.githubusercontent.com/4068757/148555707-b8440849-6e45-4bf6-a0fc-e98df3e10a24.png)

Expected:
![cursor-position-right](https://user-images.githubusercontent.com/4068757/148555737-ad60377f-04c4-43ff-a994-a6b0b7763d7f.png)

** Version information **
- OS: Windows 10 Pro 21H2
- Browser: Chrome 96
- EasyMDE version: 2.15.0

**Solution**
line 2675 in [easymde.js](https://github.com/Ionaru/easy-markdown-editor/blob/master/src/js/easymde.js) should be changed from `el.innerHTML = pos.line + ':' + pos.ch;` to `el.innerHTML = pos.line + 1 + ':' + pos.ch;`

**Comment by Ionaru** [comment]
Good catch. Should we also increase `pos.ch` by one?

In Microsoft Word, the Line and Column count both start at 1.

![image](https://user-images.githubusercontent.com/3472373/148652233-c52bee75-a5e8-41e8-8d98-6ff32cfad33f.png)

![image](https://user-images.githubusercontent.com/3472373/148652247-4f381a99-5d75-4317-a39e-fc461aed4c42.png)

Feel free to open a PR :)

**Comment by Zignature** [comment]
I'll catch `pos.ch` too and open a PR :)

**Comment by Zignature** [comment]
@Ionaru 
We overlooked one thing. The Line:Column counter starts at `0:0`. It should be `1:1`.

Right now if you put your cursor in an empty document the Line:Column counter doesn't update to `1:1`. It updates to `1:2` after a character is added to the document.

Line ~2693: `el.innerHTML = '0:0';` needs to be changed to `el.innerHTML = '1:1';`

**Comment by Ionaru** [comment]
You're right, I'll make a commit to fix that :)
