### ISSUE TITLE
Get HTML from

### ISSUE THREAD

**Issue by erossini** [Ionaru/easy-markdown-editor#382]
How can I get from EasyMDE the render HTML?

I have this code that raises a call to Blazor for every change.

```
easyMDE.codemirror.on("change", function () {
    dotNetObjectRef.invokeMethodAsync("UpdateInternalValue", easyMDE.value());
});
```

The `value` is the Markdown text. How can I get the rendered HTML code?

Thank you again,
Enrico

**Comment by Ionaru** [comment]
The editor isn't really designed to output HTML, the markdown text is the content you want to save.

But if you really want to convert that to HTML you can use the [`marked`](https://www.npmjs.com/package/marked) package: `marked.parse(easyMDE.value());`
