### ISSUE TITLE
Show '-' instead of '*' for unordered list

### ISSUE THREAD

**Issue by abudhakeer** [Ionaru/easy-markdown-editor#386]
**Describe your question**
As a beginner in web development I really love how simple yet powerful markdown editor this is. Easymde uses `*` by default for the unordered list. Can we make it configurable to use `-` instead of `*` just like we can configure bold/italics etc.? If its already supported let me know how to achieve it.

**Comment by Zignature** [comment]
> **Describe your question** As a beginner in web development I really love how simple yet powerful markdown editor this is. Easymde uses `*` by default for the unordered list. Can we make it configurable to use `-` instead of `*` just like we can configure bold/italics etc.? If its already supported let me know how to achieve it.

You can now :)

**Comment by Zignature** [comment]
unorderedListStyle: can be `*`, `-` or `+`. Defaults to `*`.

```
const editor = new EasyMDE({
	unorderedListStyle: "-"
});

**Comment by abudhakeer** [comment]
That's so faast. Thank u. @Zignature and @Ionaru  :)

**Comment by Zignature** [comment]
You're welcome. Due to the COVID-19 pandemic I have some time on my hands 😎
