### ISSUE TITLE
Upload an image add the image markdown tag without !

### ISSUE THREAD

**Issue by erossini** [Ionaru/easy-markdown-editor#387]
Finally, I have a working component for Blazor with EasyMDE! There is an issue when I upload an image. I recorded a small gif.

![easymde-image](https://user-images.githubusercontent.com/9497415/148846237-d341d0ea-de90-46ee-af20-ae43bc58f800.gif)

How you can see, after the upload, the image is added to the Markdown Editor but the `!` at the beginning is missing. I have to add manually the `!`

**Comment by erossini** [comment]
I found the issue. If there is not an image extension, it adds a link instead of a image.

**Comment by kolaente** [comment]
Did you find a solution? The uploads we do are always without an extension.
