### ISSUE TITLE
add left, center, and right alignment

### ISSUE THREAD

**Issue by imannms** [Ionaru/easy-markdown-editor#39]
### I'm submitting a...
- [] Bug report
- [x] Feature request

is it possible to add left, center, and right alignment ?

**Comment by sgbeal** [comment]
Markdown does not specify alignment features, which means that adding them to this editor would require custom extensions to markdown.

**Comment by Ionaru** [comment]
That is correct.
The editor at this moment has no control over the markdown rendering, adding custom markdown would be an extremely large effort.
