### ISSUE TITLE
Does EasyMDE support plugins ? 

### ISSUE THREAD

**Issue by atodorov** [Ionaru/easy-markdown-editor#391]
Does the editor have support for any plugins ? I am thinking about drop-in packages, which will automatically be discovered and wired up into the editor, for example providing new toolbar buttons or new features, etc. 

I am considering switching from SimpleMDE but we've got a few custom additions on top of it, plus requirements for new features which would make more sense to be implemented as plugin modules.

**Comment by Ionaru** [comment]
The editor does not support plugins at the moment. But API changes compared to SimpleMDE are pretty minimal so your custom additions you use in SimpleMDE should work without much effort.

I do think that when the inevitable ESM / CodeMirror 6 rewrite happens (#262, #324), plugins for the editor and the ability to load codemirror addons (#149) are good features to consider.
The editor itself could also be build as a core module and plugins for basic functionality (#167).
