### ISSUE TITLE
npm run test: error importing marked on v2.16.1

### ISSUE THREAD

**Issue by Zignature** [Ionaru/easy-markdown-editor#392]
**Describe the bug**
Getting an error eecuting `npm run test`.
`marked` cannot be imported.

**To Reproduce**
1. Execute `npm run test` in the main/root directory

**Expected behavior**
No errors

**Screenshots**
![import-marked-v2 16 1](https://user-images.githubusercontent.com/4068757/149615788-f380444a-1ee5-4bfe-8554-9683cae54934.gif)

**Version information**
- OS: Windows 10 Pro 21H2
- EasyMDE version: 2.16.1

**Comment by Ionaru** [comment]
Make sure the dependencies are up-to-date by running `npm ci`.

I've got multiple automated test runs proving it works 😉

**Comment by Zignature** [comment]
Ofcourse... 😏 
(*slaps himself in the face*)

**Comment by thgreasi** [comment]
This is also the error that we are getting in our library https://github.com/balena-io-modules/rendition after an `rm -r node_modules && npm i && npx tsc` using TS 3.9.
```
$ npx tsc
node_modules/easymde/types/easymde.d.ts:24:10 - error TS2616: 'marked' can only be imported by using 'import marked = require("../../@types/marked")' or a default import.

24 import { marked } from 'marked';
            ~~~~~~


Found 1 error.
```

**Comment by Ionaru** [comment]
I think `@types/marked@0.7.4` is causing the issue here. Marked changed its exports in version 4.0.0 and the types need to match it. (https://github.com/markedjs/marked/releases/tag/v4.0.0)

If upgrading is not possible, you could add `"skipLibCheck": true` to your `tsconfig.json`, that'll silence the error.
