### ISSUE TITLE
Include CSS directly from JavaScript

### ISSUE THREAD

**Issue by juanecabellob** [Ionaru/easy-markdown-editor#4]
### I'm submitting a...
- [] Bug report
- [x] Feature request

### Reproduction steps

1. ...
2. ...

### Version information
Browser type and version: Chrome 65
SimpleMDE version: Latest

### Description

Currently developers are forced to include the `css` file as an external link through HTML. In my opinion this is bad practice and should be rather packed with the module itself, so that whenever I require or import this module I don't need the extra link. In the meantime, it would be pretty useful to explicitly say so, cause as per docs you only need this when you include the module via CDNs.

**Comment by chasegiunta** [comment]
if you're using a module bundler, and adding to your project via NPM or Yarn, you can simply `import 'simplemde/dist/simplemde.min.css'`

**Comment by Ionaru** [comment]
I don't think having to add both code and styling is bad practice. Other large packages like Bootstrap, require this as well.

I do agree the README is incorrect and I will edit it.

**Comment by Ionaru** [comment]
The CSS file is packaged with the module, there are multiple ways to load the styles in that don't involve HTTP.
