### ISSUE TITLE
Include typings

### ISSUE THREAD

**Issue by chris13524** [Ionaru/easy-markdown-editor#40]
### I'm submitting a...
- [ ] Bug report
- [x] Feature request

The typings from [here](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/5344bfc80508c53a23dae37b860fb0c905ff7b24/types/simplemde) should be adapted for EasyMDE and included in this repo.

**Comment by Ionaru** [comment]
Agreed.
This should be included since https://github.com/Ionaru/easy-markdown-editor/milestone/1 is not yet finished.

**Comment by FranklinWhale** [comment]
@Ionaru Do you want to include typings in EasyMDE before v3 is finished, or alternatively, to have a PR in DefinitelyTyped for "@types/easymde"?

**Comment by Ionaru** [comment]
I'll add typings to this package, no need to use `@types/easymde`

**Comment by Ionaru** [comment]
Added the `Help wanted` label because I am not entirely sure how to add typings to an NPM package.

**Comment by FranklinWhale** [comment]
@Ionaru The typings will be available to npm after PR #44 is merged and a new version of EasyMDE is released.
