### ISSUE TITLE
How can I highlight source code in code block?

### ISSUE THREAD

**Issue by TechMaster** [Ionaru/easy-markdown-editor#404]
Hi,

I write a markdown article that has several code blocks of different programming languages. I want to hight light syntax of each code  block in editor (WYSIWYG). What should I do ?

Do I need to customize CodeMirror or just configure EasyMDE?

![image](https://user-images.githubusercontent.com/1491686/153171687-b7cc4466-8e4a-4122-82f4-de5ebd144f2f.png)

**Comment by Ionaru** [comment]
Have a look at the `codeSyntaxHighlighting` option.

**Comment by TechMaster** [comment]
There are two highlight actions:

1. When Editing
2. When Preview

What I want is highlighting code block when Edition.

`codeSyntaxHighlighting` is for previewing.
![image](https://user-images.githubusercontent.com/1491686/153183898-0cc36695-8499-4284-b62b-ee84fcb2a0f6.png)

**Comment by Ionaru** [comment]
CodeMirror has no idea the code block is a code block until the markdown is parsed, I don't think it's possible to do without some CodeMirror hacking.

**Comment by TechMaster** [comment]
Thanks  @Ionaru
CodeMirror allows to highlight syntax code blocks in Markdown.
I will try to modify your code and let you know if successfull.

**Comment by EvanZhouDev** [comment]
@TechMaster I know it's been a few years, but is there any chance that you were successful? I need this very feature 😅
