### ISSUE TITLE
Breaking change with SimpleMDE in toolbar icons

### ISSUE THREAD

**Issue by ChrisRast** [Ionaru/easy-markdown-editor#41]
### I'm submitting a...
- [x] Bug report
- [ ] Feature request

### Reproduction steps
When passing custom toolbar icons, the `no-disable` class previously used in SimpleMDE is not respected.
Check this JSFiddle: https://jsfiddle.net/myv5wgh0/.

Due to a change in early v2 (https://github.com/Ionaru/easy-markdown-editor/commit/7b147b3148671ddb7befe38c51e72cce9a8c0639#diff-510834ebe67771ad1adc3336cb7fd314R16116), `element.classList` is now used instead of the `element.className` previously in use which results in a loss of classnames. 

Also, the changes in v2 resulted in changes in the shape of the toolbar objects, which makes it a breaking change with SimpleMDE (need to add the `noDisable`property in EasyMDE).

So, no big bad breaking change, but I think it's worth mentioning it.

I found this "bug" because in a project of ours we use a different set of toolbar icons (material) and we needed to customize the actions.

### Version information
EasyMDE version: >2.0.0

**Comment by Ionaru** [comment]
Your JSFiddle doesn't work, but I see what you mean.
I'm going to consider this a bug and try to restore compatibility.

**Comment by ChrisRast** [comment]
Hot damn! Sorry for the fiddle, I don't understand why it doesn't show what I prepared.

> I'm going to consider this a bug and try to restore compatibility.

Great to see that, thank you ! =)

**Comment by mike-jewell** [comment]
I'm hitting the same problem for a different reason.  Do you have a timeline for when the typings will be updated so the noDisable and noMobile booleans will be added to the interface ToolbarIcon?

```typescript
    interface ToolbarIcon {
        name: string;
        action: string|((editor: EasyMDE) => void);
        className: string;
        title: string;
        noDisable?: boolean;
        noMobile?: boolean;
    }
```

Thanks
