### ISSUE TITLE
minHeight and maxHeight are not handled properly

### ISSUE THREAD

**Issue by wxiaoguang** [Ionaru/easy-markdown-editor#413]
**Describe the bug**

Related issue:
* https://github.com/go-gitea/gitea/pull/19003
* The related code (only a few lines): https://github.com/go-gitea/gitea/pull/19003/files

In some cases, we need to set `minHeight` and `maxHeight` at the same time.

However, although the EasyMDE document has described the details of `minHeight`/`maxHeight` handling, the current logic is not ideal.

**To Reproduce**

Current logic: 

`{minHeight: '80px', maxHeight: 'calc(100vh-200px)'}` becomes `style="min-height: calc(100vh-200px); height: calc(100vh-200px)"`

Then users are not able to make the heights correct in some cases.

**Expected behavior**

Just pass `minHeight` to `min-height` and `maxHeight` to `max-height` as they are.

**Comment by Ionaru** [comment]
We may be able to change the behaviour when both values are set.
The current behaviour was introduced in https://github.com/Ionaru/easy-markdown-editor/pull/222 as a fix for https://github.com/Ionaru/easy-markdown-editor/issues/206 and possibly https://github.com/Ionaru/easy-markdown-editor/issues/212.

**Comment by wxiaoguang** [comment]
According to standard, we do not need to process if max-height is less than min-height, in such case, min-height works.

https://developer.mozilla.org/en-US/docs/Web/CSS/min-height
https://developer.mozilla.org/en-US/docs/Web/CSS/max-height

max-[height](https://developer.mozilla.org/en-US/docs/Web/CSS/height) overrides height, but [min-height](https://developer.mozilla.org/en-US/docs/Web/CSS/min-height) overrides max-height.

The element's height is set to the value of min-height whenever min-height is larger than [max-height](https://developer.mozilla.org/en-US/docs/Web/CSS/max-height) or [height](https://developer.mozilla.org/en-US/docs/Web/CSS/height).

**Comment by wxiaoguang** [comment]
I see the plan about "3.0 rewrite", close this one as not planned?
