### ISSUE TITLE
Bootstrap CDN Down

### ISSUE THREAD

**Issue by aboqasem** [Ionaru/easy-markdown-editor#416]
**Describe the bug**
Font Awesome icons disappear because Bootstrap CDN is down.

**To Reproduce**
1. Go to https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css

**Expected behavior**

**Screenshots**

![Screenshot 2022-03-23 at 4 28 31 PM](https://user-images.githubusercontent.com/62098043/159655896-e9467198-6837-4ddd-b19c-dfc98b5d8978.png)

**Version information**
- OS: macOS 12.2.1
- Browser: Brave V1.36.119
- EasyMDE version: ^2.16.1

**Comment by Ionaru** [comment]
You can always provide your own FontAwesome file and set `autoDownloadFontAwesome` to `false`.

Anyway, CDN seems to be back up, so closing this.
