### ISSUE TITLE
Some toolbar button icons not displayed

### ISSUE THREAD

**Issue by zspitz** [Ionaru/easy-markdown-editor#426]
**Describe the bug**
When setting some custom buttons, the icons aren't displayed.

**To Reproduce**
```
let ret = new EasyMDE({
    element: document.getElementById('editor'),
    toolbar: [{
        name: 'save',
        action: () => { },
        className: 'fa-solid fa-floppy-disk',
        title: 'Save file'
    }, {
        name: 'saveas',
        action: () => { },
        className: 'fa-solid fa-floppy-disk-pen',
        title: 'Save file as'
    }]
});
```

**Expected behavior**
Both buttons will display their icon.

**Screenshots**

![image](https://user-images.githubusercontent.com/312166/167797793-6944c7e1-a38a-4dfd-bb76-cf7c555fbbd3.png)

The button is there and calls the action when clicked, but the icon is not displayed.

**Version information**
- OS: Windows
- Browser: Edge 97 (embedded WebView2)
- EasyMDE version: 2.16.1

**Additional context**
I have noticed that buttons which have this problem, don't have a pseudo-`::before` element in the Elements view:

![image](https://user-images.githubusercontent.com/312166/167798695-fc8d3df1-cde2-41cc-8c23-96e0ea19e5bc.png)

which is consistent with the described behavior, because FontAwesome icons are inserted via the `::before` pseudo-selector.

**Comment by Ionaru** [comment]
[`fa-solid fa-floppy-disk`](https://fontawesome.com/icons/floppy-disk) looks like a Fontawesome 5 or 6 icon and is not available in the FontAwesome version the editor uses by default (4.7). The 4.7 equivalent is [`fa fa-floppy-o`](https://fontawesome.com/v4/icon/floppy-o).

[`fa-solid fa-floppy-disk-pen`](https://fontawesome.com/icons/floppy-disk-pen) is a *Pro* icon and can only be used when you load in a *Pro* version of FontAwesome.

**Comment by Ionaru** [comment]
With FontAwesome 6 loaded:

![image](https://user-images.githubusercontent.com/3472373/169311201-ae6d009c-e59b-4477-8be6-1ab9e89b0ea0.png)
