### ISSUE TITLE
API hooks for image/file uploading

### ISSUE THREAD

**Issue by LinusU** [Ionaru/easy-markdown-editor#46]
### I'm submitting a...
- [x] Feature request

We would like to give our users the ability to upload images and files, and I think that GitHub has solved this really nice. In order to implement this, I would love it if there was some way to register hooks for when a file is dropped onto the editor.

To be clear, I would not like the editor to do anything regarding the actual uploading of the files. Just a hook that calls my own function when a file has been dropped.

My own code could then upload the file, and insert the correct markdown syntax for it to be displayed ☺️ 

I'd be happy to help contribute code for this, please let me know what you think!

**Comment by Ionaru** [comment]
Sounds like a cool feature for the editor!
Will need to read up on how HTML handles files, but it sounds doable.
https://developer.mozilla.org/en-US/docs/Web/API/HTML_Drag_and_Drop_API/File_drag_and_drop

**Comment by sgbeal** [comment]
All of those features can be implemented purely client-side, without hooks from this code. Select the elements you want and add the desired event handlers. That doesn't sound like something this code base needs to add/maintain, considering that the small minority of clients who'd make use of it could just as easily hook in the events themselves.

**Comment by LinusU** [comment]
Just saw that codemirror actually exposes the `"dragstart"`, `"dragenter"`, `"dragover"`, `"dragleave"`, and `"drop"` events, so this could actually be possible without any further work here. Would personally think it would be very neat if the library could handle this, and showing a "Drop to add image" when hovering an image over, when being passed something like a `onImageDrop` function...

Hopefully I'll get some time to try out the existing events soon and report back how the feels/if it works ☺️

**Comment by roipoussiere** [comment]
I'm working on this, I will send a PR soon. :)
