### ISSUE TITLE
Can the preview pane go full-height?

### ISSUE THREAD

**Issue by ryangjchandler** [Ionaru/easy-markdown-editor#468]
**Describe your question**
At the moment, the preview pane / tab is fixed to the height of the editor. Is there any recommended way to get the preview to be the full height of the content to prevent scrolling?

**Comment by Ionaru** [comment]
You can style the editor to use as much height as it needs, but that includes both the edit and preview screens.

With some added CSS you can probably have the height change when the preview is shown, there's a class that is changed when previewing.
