### ISSUE TITLE
I want to download markdown text using js only (no server)

### ISSUE THREAD

**Issue by MohamedAliRashad** [Ionaru/easy-markdown-editor#470]
I think this is an easy thing to do, but the problem is that i have no idea how to do it

**Comment by Ionaru** [comment]
Yes it's very easy, you can use `easymde.value()` to get the markdown text from the editor.

https://github.com/Ionaru/easy-markdown-editor#editor-functions

**Comment by MohamedAliRashad** [comment]
@Ionaru it worked, thaks
