### ISSUE TITLE
Parishioner21$

### ISSUE THREAD

**Issue by Gam3356** [Ionaru/easy-markdown-editor#475]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Version information**
- OS: [e.g. Windows, MacOS]
- Browser: [e.g. Chrome 72]
- EasyMDE version: [e.g. 2.5.1]

**Additional context**

**Comment by Gam3356** [comment]
Thank you guys! Willie Parish

**Comment by Ionaru** [comment]
I have no idea what this is.
