### ISSUE TITLE
Markdown button classnames can overlap with user-based classnames

### ISSUE THREAD

**Issue by stsrki** [Ionaru/easy-markdown-editor#493]
We got a report from one of our users that Markdown buttons are broken.

![image](https://user-images.githubusercontent.com/900302/186154038-969593b5-870e-4612-a07e-d9abbf6cfae7.png)

The original issue https://github.com/Megabit/Blazorise/issues/4060

---

Basically, it seems that the class names that are used by this library can overlap with Bootstrap or with any other user classes. They are too generic with names `table`, `bold`, `italic`, etc.

I have tried to change them dynamically after the MDE instance is created with the following code:

```js
const easyMDE = new EasyMDE(mdeOptions);

if (easyMDE.options.toolbar) {
    for (let index = 0; index < easyMDE.options.toolbar.length; ++index) {
        const element = easyMDE.options.toolbar[index];

        if (element && element.name && !element.name.startsWith("mde-")) {
            element.name = "mde-" + element.name;
        }
    }
}
```

and it kinda works but not 100%. From what I can observe, the `.toolbar` is a global object, and any change to it changes all of the instances. If there are 5 editors on a page, a race condition happens, and one or two editors are rendered without the previously added `"mde-"` prefix.

---

My question is.

1. How can I override MDE classnames? Is it even possible to do?
2. Can MDE come with predefined classnames that include a prefix? Eg. `table` becomes `mde-table`

**Comment by Ionaru** [comment]
This was brought up before in https://github.com/Ionaru/easy-markdown-editor/pull/465, but I am hesitant to make this change in the current (v2) version.

Technically the class names aren't part of the public API and therefor shouldn't be breaking change, but they are very much a public part of the rendered element. I'm afraid it will break a lot of custom styling from users.

**Comment by stsrki** [comment]
Can it be optional? I can think of two way

1. Add new boolean option `prefixToClasses`. And if true it will add `mde-`(or anything else). By default it can be `false`.
2. Add a new field to the toolbar button/element object, eg.

```diff
{
    name: "heading",
--    buttonClassName: "mde-heading",
    action: EasyMDE.toggleHeadingSmaller,
    className: "fa fa-header",
    title: "Headers",
}
```

Both ways are opt-in and not breaking changes.

**Comment by Ionaru** [comment]
Good ideas! I think `prefixToClasses` will be easier to implement.

**Comment by PackeTsar** [comment]
I'm having this issue as well. Bootstrap4 apparently has a class name conflict and set's 100% width on any elements with `class="table"`. Implementing `prefixToClasses` seems like a good fix.

**Comment by Ionaru** [comment]
The `toolbarButtonClassPrefix` is now available in the `@next` version, this should resolve the conflict with Bootstrap.

**Comment by stsrki** [comment]
@Ionaru Thank you. Can you tell me where is the next release expected to be released?

**Comment by Ionaru** [comment]
[2.18.0](https://github.com/Ionaru/easy-markdown-editor/releases/tag/2.18.0) has now been released :)
