### ISSUE TITLE
Initial Value not rendering until click 

### ISSUE THREAD

**Issue by SmitharyZach** [Ionaru/easy-markdown-editor#499]
**Describe the bug**
I am setting an initial value with EasyMDE. The initial value only appears after I click into the editor 

**Expected behavior**
The initial value to load on page load

**Screenshots**
On page load: 
<img width="586" alt="image" src="https://user-images.githubusercontent.com/36892129/190706822-d8a6f451-3dc1-4656-9d83-1e71da0a8c4a.png">

After clicking in:
<img width="562" alt="image" src="https://user-images.githubusercontent.com/36892129/190706841-accc03f6-85a2-4ba6-a132-8397b83198b0.png">

**Version information**
Chome browser
current version of easyMDE

**Additional context**
Here is my code:

    const benefitsMDE = new EasyMDE({
        element: document.getElementById('membership-benefits-text-area'),
        initialValue: "${membershipDetails.membershipBenefits}",
        hideIcons: [
            "guide",
            "heading",
            "quote",
            "italic",
            "bold",
            "strikethrough",
            "upload-image",
            "image",
            "side-by-side",
            "link",
            "fullscreen",
        ],
        maxHeight: "200px"
    });

**Comment by Ionaru** [comment]
I was not able to reproduce this. Maybe something goes wrong with the value insertion? `"${membershipDetails.membershipBenefits}"` suggests there's some kind of templating engine at work.

My complete HTML:

```html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Example / Preview</title>
    <link rel="stylesheet" href="https://unpkg.com/easymde/dist/easymde.min.css">
    <script src="https://unpkg.com/easymde/dist/easymde.min.js"></script>
</head>

<body>
    <textarea id="test-textarea"></textarea>
    <script>
        const easyMDE = new EasyMDE({
            element: document.getElementById("test-textarea"),
            initialValue: "Text I wanna show when the page loads.",
            hideIcons: [
                "guide",
                "heading",
                "quote",
                "italic",
                "bold",
                "strikethrough",
                "upload-image",
                "image",
                "side-by-side",
                "link",
                "fullscreen",
            ],
            maxHeight: "200px"
        });
    </script>
</body>

</html>
```

Result:
![image](https://user-images.githubusercontent.com/3472373/190869434-f1fc952d-7a20-4723-a422-0ab331c1b592.png)

**Comment by SmitharyZach** [comment]
@lonaru thanks for the help! This was an issue with my code not the editor. Great editor by the way! Cheers

**Comment by carlos3duardo** [comment]
@SmitharyZach I have the same problem here, and it's driving me crazy. I can't find what is wrong.
How did you fix it?

**Comment by SmitharyZach** [comment]
@carlos3duardo try adding these options to the initialization of EasyMDE

autoSave: false,
autoRefresh: {delay: 500}

**Comment by carlos3duardo** [comment]
@SmitharyZach 

`autosave: false` cause a error. The correct is `autosave: { enabled: false }`, but my code was already like this.

With `autoRefresh: { delay: 500}` WORKS!!! Thank you soo much!

After it worked I went to read the documentation for this option:

> **autoRefresh**: Useful, when initializing the editor in a hidden DOM node. If set to { delay: 300 }, it will check every 300 ms if the editor is visible and if positive, call CodeMirror's [refresh()](https://codemirror.net/doc/manual.html#refresh).

*"when initializing the editor in a hidden DOM node"* this is exactly my case. Man, how inattentive I was.

Thanks again.

**Comment by SmitharyZach** [comment]
ayy! awesome!
