### ISSUE TITLE
update codemirror to 6

### ISSUE THREAD

**Issue by KiaraGrouwstra** [Ionaru/easy-markdown-editor#505]
it looks like the [`codemirror`](https://github.com/Ionaru/easy-markdown-editor/blob/master/package.json#L24) dependency is behind on their switch to a [newer repo](https://github.com/codemirror/dev).
it would be nice if we could update to that one.
the codemirror people have detailed the migration process in a [guide](https://codemirror.net/docs/migration/).

**Comment by Ionaru** [comment]
The codemirror upgrade will be handled in https://github.com/Ionaru/easy-markdown-editor/issues/447, the current codebase relies very heavily on version 5's API and upgrading would need a rewrite anyway.

**Comment by KiaraGrouwstra** [comment]
closing as dupe of #324, thanks.
