### ISSUE TITLE
Newlines not being displayed when setting value

### ISSUE THREAD

**Issue by ivakam** [Ionaru/easy-markdown-editor#51]
When setting the value to a markdown string that includes newline characters the entire string is displaying as one line when using `myEditor.value('myMarkdownString')`.

Either I'm doing it wrong or it's not parsing the newlines correctly. Any help appreciated

EasyMDE version: 2.5.1

**Comment by Ionaru** [comment]
The newline character is `\n`.

What OS and browser are you using?

**Comment by Ionaru** [comment]
Does the text appear as `firstLine\nSecondLine` in the editor?
If this is the case then I suspect the `\n` is being escaped to `\\n`.

You're welcome! I thought the same about the project and that it would really be a shame to let it die.

**Comment by ivakam** [comment]
It just appears as nothing from what I can tell. Just a single line with an all-caps "NEW LINE" sometimes appearing (I have not been able to reliably reproduce it).

Some screenshots for clarity:

Input value:
https://i.imgur.com/bQ5AVGr.png

Appearance in editor (all contained within a single presentation span in the CodeMirror)
https://i.imgur.com/LsrYGg1.png

**Comment by Ionaru** [comment]
I'm not sure how newlines work in the editor you are using, but maybe the newlines in that text block are not converted to newline characters.

The most reliable way to insert newlines in your text is to add `\n` (or `\r` or `\r\n`) in the text you are typing. The code blocks on https://easymde.tk/ show an example of this.

**Comment by ivakam** [comment]
Ah that makes sense! 
I guess my actual problem then is to figure out how to insert those, but that's for me to figure out. The editor I'm using is just SimpleMDE with some styling modifications.

Thanks a bunch for the quick support!
