### ISSUE TITLE
Table toolbar icon appears on it's own row

### ISSUE THREAD

**Issue by raharrison** [Ionaru/easy-markdown-editor#516]
**Describe the bug**
The table toolbar icon takes up it's own row in the main toolbar. The issue is visible in the main demo page "toolbar Customization" example. Seems specific to just the table icon and not others.

**To Reproduce**
1. Go to https://easy-markdown-editor.tk/
2. View "Toolbar Customization" example

**Expected behavior**
The table icon should appear alongside other icons in the same row

**Screenshots**
![image](https://user-images.githubusercontent.com/2327200/211650201-8532d738-1077-4325-b32a-db92975609f2.png)

**Version information**
- Browser: Chrome
- EasyMDE version: 2.18.0

**Comment by Ionaru** [comment]
Ah, caused by https://github.com/Ionaru/easy-markdown-editor/issues/493, I'll need to set the `toolbarButtonClassPrefix` option on the demo website :)

**Comment by raharrison** [comment]
Looks like https://easy-markdown-editor.tk/ is down now btw, but my issue is resolved with that property. Thanks!
