### ISSUE TITLE
`upload-image` is missing from `ToolbarButton` types

### ISSUE THREAD

**Issue by p3yman** [Ionaru/easy-markdown-editor#521]
**Describe the bug**
`upload-image` is missing from `ToolbarButton` types and it cause error on TypeScript. 

**To Reproduce**
1. Try to use `upload-image` on a custom toolbar with type `SimpleMDE.Options` like:

```javascript
const editorOptions: SimpleMDE.Options = {
  toolbar: [
    'bold',
    'italic',
    'strikethrough',
    'upload-image',
  ],
};
```

**Expected behavior**
It should be included in `easymde.d.ts`

**Version information**
- EasyMDE version: 2.18.0

**Comment by borodean** [comment]
PR: https://github.com/Ionaru/easy-markdown-editor/pull/520.

**Comment by Ionaru** [comment]
Fixed in https://github.com/Ionaru/easy-markdown-editor/pull/520
