### ISSUE TITLE
support code mirror 6

### ISSUE THREAD

**Issue by y0va** [Ionaru/easy-markdown-editor#563]
Codemirror5 seems to be near eol, got tagged as legacy. Is there work put on supporting [cm6](https://github.com/codemirror/dev)?

**Comment by Ionaru** [comment]
The current version (2) of easy-markdown-editor will never support CodeMirror 6, there are just too many changes needed.

CodeMirror 6 will be included in https://github.com/Ionaru/easy-markdown-editor/issues/447.
