### ISSUE TITLE
What about text color & styling

### ISSUE THREAD

**Issue by siMobin** [Ionaru/easy-markdown-editor#581]
Since Gmail's composer supports text styling, why not **[easy-markdown-editor](https://github.com/Ionaru/easy-markdown-editor)**

Also dark mode compatibility

**Screenshot**

- Gmail
![image](https://github.com/Ionaru/easy-markdown-editor/assets/102217786/5c3a2883-ba95-4df1-9a8e-84b67a8b6e5e)

- My custom-made paintbrush (not satisfied with it)
![image](https://github.com/Ionaru/easy-markdown-editor/assets/102217786/ef87277b-dda9-458f-9e1a-1516f510b716)

**Comment by evansharp** [comment]
These are not part of the markdown spec, so can't be implemented in a markdown editor.
