### ISSUE TITLE
forceSync=true is not working.

### ISSUE THREAD

**Issue by melloware** [Ionaru/easy-markdown-editor#585]
**Describe the bug**
The docs for `forceSync` say it will automatically sync to the original textArea but I am not seeing that behavior.

**To Reproduce**

Reproducer:  https://stackblitz.com/edit/easymde-urbxmv?file=index.html

1. Start typing.  I can see that forceSync calls cm.save()`
2. View the HTML source and you will see the original textArea does not contain the new text.

**Expected behavior**

The textArea should contain the edited text

**Comment by melloware** [comment]
My bad its working.

**Comment by jose-mr** [comment]
> My bad its working.

Did you have to make any changes to the code to make it work? It is also not working for me with just the forceSync option set to true.
