### ISSUE TITLE
Can not select text on mobile

### ISSUE THREAD

**Issue by askosh** [Ionaru/easy-markdown-editor#60]
### I'm submitting a...
- [x] Bug report
- [ ] Feature request

### Reproduction steps

1. Double tap on a word to select it
2. It selects it and deselects it, making it impossible to select text

### Version information
Browser type and version: Latest Android Chrome
EasyMDE version: Latest from unpkg

This also happens on the demo version of EasyMDE.

**Comment by Ionaru** [comment]
You can still select text by holding down on the text for a second.

In the meantime I'll investigate why double-tap isn't working.

**Comment by Ionaru** [comment]
I am noticing some weird behaviour when attempting to select a piece of text while the cursor is in the editor. It flickers and doesn't keep the selection.

**Comment by Ionaru** [comment]
I'm getting the same behaviour on https://codemirror.net/demo/theme.html, this appears to be a CodeMirror issue, not one with EasyMDE.

Please open an issue with [CodeMirror](https://github.com/codemirror/CodeMirror/) if there isn't one already.
