### ISSUE TITLE
Don't commit dist folder?

### ISSUE THREAD

**Issue by roipoussiere** [Ionaru/easy-markdown-editor#65]
I don't find how is that useful to commit the `dist` folder, since it's generated with gulp.

Some drawbacks:
- redundancy;
- always creates conflicts, so many pull-requests can not be merged automatically and it makes the update more difficult, so it's annoying both for maintainers and developers;
- we are never really sure that the files in the dist folder are consistent with the sources before to run `gulp`;
- this make the git history huge.

**Comment by Ionaru** [comment]
I completely agree, this is a change I've been wanting to make for a long time.
