### ISSUE TITLE
How does saving images work in easy-markdown-editor?

### ISSUE THREAD

**Issue by sunk818** [Ionaru/easy-markdown-editor#7]
https://simplemde.com/

I read the text and it mentions being able to have images.

Do we have to upload to imgur ourselves, or does the product accept a copy & paste into screen and uploads to imgur for us?

**Comment by Ionaru** [comment]
Images need to be hosted on an image-sharing website like Imgur to work. EasyMDE currently does not support copy-pasting images into the editor.

**Comment by sunk818** [comment]
I see. That's like every other Markdown Editor available. Made it sound like it was some special feature. Okay, thank you.

**Comment by maddyfarr** [comment]
Has this changed in 2020? It seems as though you can now upload images/ paste in a screen shot? Thank-you!

**Comment by floogy** [comment]
Somebody did create a working Paste and Upload Image from clipboard for SimpleMDE, which this project forked from. 

**Required code may be right here:**
https://github.com/gautiermichelin/simplemde-markdown-editor

User created this in response to https://github.com/sparksuite/simplemde-markdown-editor/issues/328

PS: Generating and saving a real image file in the background is essential to keep massive amounts of base64 image data out of your database tables.
