### ISSUE TITLE
display problem

### ISSUE THREAD

**Issue by hi-gouzi** [Ionaru/easy-markdown-editor#84]
One of the problems with SimpleMDE is that when you copy and paste a large chunk of text, the top half of the text appears as a large blank space, and you have to manually click to get the text to appear
when i copy and paste，It is displayed like this
![image](https://user-images.githubusercontent.com/38695280/56790252-a8bd1f00-6836-11e9-84a2-ed58771d28af.png)

At this time, I need to manually click on the area.
then, It is displayed like this
![image](https://user-images.githubusercontent.com/38695280/56790365-f76ab900-6836-11e9-93a6-3186490773e4.png)
I see the same demo on the example.

**Comment by mxgl** [comment]
Is the cause of this known?

**Comment by A-312** [comment]
> Is the cause of this known?

![image](https://user-images.githubusercontent.com/18501150/73772793-2a0bef80-4781-11ea-9ed8-28bd8c3a20bd.png)

`top` value doesn't refresh well :/
