### ISSUE TITLE
Demo site is down

### ISSUE THREAD

**Issue by sunjam** [Ionaru/easy-markdown-editor#89]
Hi, the demo site for easyMDE [appears to be down](https://easymde.tk/).

**Comment by Ionaru** [comment]
Thank you for the report, will figure out what's wrong with the webserver

**Comment by Ionaru** [comment]
The website should now be online and stable again, my apologies for the interruption.

**Comment by AndiLeni** [comment]
@Ionaru the site is still not accessible for me. Maybe you should check again. 

Kind regards 
Andi

**Comment by Ionaru** [comment]
_grumble_ _grumble_ _grumble_

Some kind of issue with docker is causing nginx to not let connections through, I still haven't found the cause but a restart of the docker daemon seems to have fixed it for now.

Thank you for notifying me!

**Comment by cbaconnier** [comment]
Hi @Ionaru, I was passing by and saw that the demo seems down

**Comment by Ionaru** [comment]
Thanks for the report, this is a recurring issue I'm having with nginx and Docker for Windows.

**Comment by Ionaru** [comment]
The website is online again, apologies for the interruption.
