### ISSUE TITLE
Accented "A" appearing at the end of cursor

### ISSUE THREAD

**Issue by dististik** [Ionaru/easy-markdown-editor#91]
**Describe the bug**
An accented A is appended to the end of the cursor in the text area and on blank lines when using EasyMDE in Chrome and NW.js.

**To Reproduce**
1. Download EasyMDE's CSS and JavaScript files from UNPKG CDN.
2. Link the stylesheet and script to an HTML file from a local directory.
3. Load EasyMDE onto a textarea with all of the default settings.
4. Open the HTML file in Chrome.
5. Click in the text area.

**Expected behavior**
The cursor should just be a blinking line.

**Screenshots**
The cursor has an accented A appended to it.

Example:
![](https://i.imgur.com/EEJYHGq.png)

** Version information **
- OS: Windows
- Browser: Chrome 74.0.3729.169
- EasyMDE version: 2.6.0

**Additional context**
I also have the multilingual IME for Japanese installed on this machine, although I'm not sure if that would effect anything in this problem when typing in English.

**Comment by Ionaru** [comment]
This is caused by a wrong charset on your webpage.
Try adding this in the `<head>`
```html
<meta charset="UTF-8">
```

**Comment by dististik** [comment]
Oh goodness, this is a silly mistake on my behalf. Thank you!
