### ISSUE TITLE
Changing formatting from Ordered list to Unordered list fails, results in console error 

### ISSUE THREAD

**Issue by roryok** [Ionaru/easy-markdown-editor#92]
**Describe the bug**
Changing formatting from Ordered list to Unordered list fails, results in console error `Uncaught SyntaxError: Invalid regular expression: /*/: Nothing to repeat`

**To Reproduce**
1. Go to 'https://easymde.tk/'
2. Enter some text 
3. Select, click on "ordered list" button from toolbar
4. Click on "unordered" list

**Expected behavior**
List will change from ordered to unordered

**Screenshots**
Nothing happens, error appears in console. 

** Version information **
- OS: [MacOS Sierra]
- Browser: [Chrome 74]
- EasyMDE version: [2.6.0]

**Comment by roryok** [comment]
I added a PR for a workaround here: https://github.com/Ionaru/easy-markdown-editor/pull/93

**Comment by Ionaru** [comment]
Good find! I'll review the PR.
